const majors = [
  "Africana Studies",
  "American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Applied Mathematics-Biology",
  "Applied Mathematics-Computer Science",
  "Applied Mathematics-Economics",
  "Archaeology and the Ancient World",
  "Architecture",
  "Astronomy",
  "Behavioral Decision Sciences",
  "Biochemistry and Molecular Biology",
  "Biology",
  "Biomedical Engineering",
  "Biophysics",
  "Business, Entrepreneurship, and Organizations",
  "Chemical Physics",
  "Chemistry",
  "Classics",
  "Cognitive Neuroscience",
  "Cognitive Science",
  "Comparative Literature",
  "Computational Biology",
  "Computer Science",
  "Computer Science-Economics",
  "Contemplative Studies",
  "Development Studies",
  "Early Modern World",
  "East Asian Studies",
  "Economics",
  "Education Studies",
  "Egyptology and Assyriology",
  "Engineering",
  "Engineering and Physics",
  "English",
  "Environmental Studies",
  "Ethnic Studies",
  "French and Francophone Studies",
  "Gender and Sexuality Studies",
  "Geological Sciences",
  "Geology-Biology",
  "Geology-Chemistry",
  "Geology-Physics/Mathematics",
  "German Studies",
  "Health and Human Biology",
  "Hispanic Literatures and Cultures",
  "History",
  "History of Art and Architecture",
  "International and Public Affairs",
  "International Relations",
  "Italian Studies",
  "Judaic Studies",
  "Latin American and Caribbean Studies",
  "Linguistics",
  "Literary Arts",
  "Mathematics",
  "Mathematics-Computer Science",
  "Mathematics-Economics",
  "Medieval Cultures",
  "Middle East Studies",
  "Modern Culture and Media",
  "Music",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Physics and Philosophy",
  "Political Science",
  "Portuguese and Brazilian Studies",
  "Psychology",
  "Public Health",
  "Public Policy",
  "Religious Studies",
  "Science, Technology, and Society",
  "Slavic Studies",
  "Social Analysis and Research",
  "Sociology",
  "South Asian Studies",
  "Statistics",
  "Theatre Arts and Performance Studies",
  "Undecided",
  "Urban Studies",
  "Visual Art",
];

const pronouns = (
  <datalist id="pronouns">
    <option value="he/him" />
    <option value="she/her" />
    <option value="they/their" />
    <option value="ze/hir" />
  </datalist>
);
const greekLife = [
  "Alpha Chi Omega",
  "Alpha Delta Phi Society",
  "Alpha Phi Alpha",
  "Beta Omega Chi",
  "Delta Gamma",
  "Delta Phi",
  "Delta Sigma Theta",
  "Delta Tau",
  "Kappa Alpha Theta",
  "Kappa Alpha Psi",
  "Kappa Delta",
  "Theta Alpha",
  "Zeta Delta Xi",
];

const instruments = [
  "Bass",
  "Cello",
  "Clarinet",
  "Drums",
  "Flute",
  "Guitar",
  "Piano",
  "Saxophone",
  "Trumpet",
  "Violin",
  "Vocals",
];

const pickUpSports = [
  "Basketball",
  "Football",
  "Soccer",
  "Spikeball",
  "Table Tennis",
  "Tennis",
  "Ultimate Frisbee",
  "Volleyball",
];

const varsitySports = [
  "Baseball",
  "Basketball",
  "Crew",
  "Cross Country",
  "Equestrian",
  "Fencing",
  "Field Hockey",
  "Football",
  "Ice Hockey",
  "Lacrosse",
  "Rugby",
  "Sailing",
  "Soccer",
  "Softball",
  "Swimming and Diving",
  "Tennis",
  "Track and Field",
  "Volleyball",
  "Water Polo",
  "Wrestling",
];

const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const states = [
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Federated States of Micronesia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Marshall Islands",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Palau",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Island",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

const CandAinterests = [
  "Academic and Scientific Research",
  "Architecture",
  "Art and Design",
  "Astronomy",
  "Finance and Economics",
  "Business and Marketing",
  "Computer Science and Web Design",
  "Cultural and Social Studies",
  "Data Science",
  "Education",
  "Engineering",
  "English",
  "Environment and Sustainability",
  "Entrepreneurship",
  "Health Care and Medicine",
  "History and Philosophy",
  "Innovation and Technology",
  "International Relations",
  "Journalism and Media",
  "Government, Law, and Public Policy",
  "Linguistics",
  "Math and Statistics",
  "Natural and Physical Sciences",
  "Performing Arts",
];

const GHinterests = [
  "Animals and Pets",
  "Artistic Creation",
  "Baking and Cooking",
  "Board and Card Games",
  "Concerts and Festivals",
  "Clubs and Nightlife",
  "Home and Garden",
  "Media and Podcasts",
  "Movies",
  "Music",
  "Photography",
  "Plane, Trains, and Automobiles",
  "Playing Music ",
  "Reading and Writing",
  "Shopping and Fashion",
  "Theatre and Performing Arts",
  "Traveling",
  "TV/Shows",
  "Video Games",
];

const PAandWinterests = [
  "Baseball",
  "Basketball",
  "Boxing, MMA, and Wrestling",
  "Cycling",
  "Football",
  "Golf",
  "Hiking, Backpacking, and Camping",
  "Hunting and Fishing",
  "Meditation and Yoga",
  "Motor Sports",
  "Food and Nutrition",
  "Physical Exercise and Working Out",
  "Sleep and Recovery",
  "Soccer",
  "Swimming and Diving",
  "Tennis",
  "Track and Field",
  "Water Sports",
  "Winter Sports",
];

const courseList = [
  ["AFRI 1050A", "Advanced RPM Playwriting"],
  ["AFRI 0090", "An Introduction to Africana Studies"],
  ["AFRI 0600", "Race, Gender, and Urban Politics"],
  ["AFRI 0670", "Global Black Radicalism"],
  ["AFRI 0750", "Race and Political Theory"],
  ["AFRI 0800", "Theorizing Racism"],
  ["AFRI 0850", "The Politics of Gender in the Caribbean Novel"],
  ["AFRI 1050D", "Intermediate RPM Playwriting"],
  ["AFRI 1050E", "RPM Playwriting"],
  ["AFRI 1110", "Voices Beneath the Veil"],
  ["AFRI 1200X", "The Art and Imagination of Josephine Baker"],
  ["AFRI 1205", "Racial Passing in Literature, Life, and Film"],
  ["AFRI 1230", "Black Protest Music"],
  ["AFRI 1330", "Africana Studies Junior Seminar"],
  ["AFRI 1420", "Caribbean Imaginations: Writing and Cultural Production"],
  ["AFRI 1920", "Health Inequality in Historical Perspective"],
  ["AFRI 1970", "Independent Reading and Research"],
  [
    "AFRI 2002",
    "Theories of Africana Thought: Literary and Expressive Cultures",
  ],
  ["AFRI 2030", "Sylvia Wynter and the Genres of the Human"],
  ["AFRI 2101", "Methods in Africana Studies"],
  ["AFRI 2104", "Theorizing the Black Diaspora"],
  ["AFRI 2450", "Exchange Scholar Program"],
  ["AFRI 2980", "Graduate Level Independent Reading and Research"],
  ["AFRI 2990", "Thesis Preparation"],
  ["AFRI XLIST", "Courses of Interest to Concentrators in Africana Studies"],
  ["AMST 1611A", "Making America: Twentieth-Century U.S"],
  ["AMST 1611O", "Race and Early American Film: The Birth of an Industry"],
  ["AMST 1700N", "Public Memory: Testimony, Memorial, Ritual"],
  ["AMST 1800", "Honors Seminar"],
  ["AMST 1902K", "Collections and Colonialism"],
  ["AMST 1903A", "Missing: Museums, Memorials, &amp; Gentrification"],
  ["AMST 1906U", "Culture as History: Making the 20th Century United States"],
  ["AMST 1900P", "Essaying Culture"],
  ["AMST 1901B", "Form Matters: Contemporary Short Fiction"],
  ["AMST 1970", "Independent Reading and Research"],
  ["AMST 2010", "Introduction to Interdisciplinary Methods"],
  [
    "AMST 2220Y",
    "Aesthetics of Relation: Minoritarian Gestures in the Visual Realm",
  ],
  ["AMST 2221", "Museum Exhibitions"],
  ["AMST 2450", "Exchange Scholar Program"],
  ["AMST 2525", "American Studies MA Capstone"],
  ["AMST 2950", "Independent Reading and Research in Public Humanities"],
  ["AMST 2990", "Thesis Preparation"],
  ["ETHN 1000", "Introduction to American/Ethnic Studies"],
  ["AMST 2660", "Projects in Public Humanities"],
  ["AMST 2920", "Independent Reading and Research"],
  ["AMST 2921", "Independent Reading and Research"],
  ["AMST 2922", "Independent Reading and Research"],
  ["AMST 2923", "Independent Reading and Research"],
  ["ETHN 1200D", "Latinx Literature"],
  ["ETHN 1750L", "Latina Feminisms"],
  ["ETHN 1751B", "Feeling Minor: Race, Affect, and Asian America"],
  ["ETHN 1910", "Independent Study"],
  ["ETHN 1920", "Senior Thesis"],
  ["PHUM 1904", "Power + Water: Material Culture and its Environmental Impact"],
  ["PHUM 2025", "Semester Practicum in Public Humanities"],
  ["PHUM 2010", "Introduction to Public Humanities"],
  ["PHUM 2014", "Museum Interpretation Practices"],
  ["PHUM 2015", "Public Art: History, Theory, and Practice"],
  ["PHUM 2020", "Methods in Public Humanities"],
  ["PHUM 2060", "Projects in Public Humanities"],
  ["PHUM 2065", "Independent Reading and Research in Public Humanities"],
  ["ANTH 0066D", "Who Owns the Past?"],
  ["ANTH 0066J", "So You Want to Change the World?"],
  ["ANTH 1111", "Anthropology of China"],
  ["ANTH 0100", "Introduction to Cultural Anthropology"],
  ["ANTH 0300", "Culture and Health"],
  ["ANTH 0800", "Sound and Symbols: Introduction to Linguistic Anthropology"],
  ["ANTH 1031", "Classic Mayan Civilization"],
  ["ANTH 1115", "Anthropology of the Chinese Diaspora"],
  [
    "ANTH 1145",
    "Barbarians and Bandits: Exploring Subaltern Resilience and State Power",
  ],
  ["ANTH 1225", "Gendering Migration and Diasporas"],
  ["ANTH 1236", "Urban Life: Anthropology in and of the City"],
  ["ANTH 1242", "Bioethics and Culture"],
  ["ANTH 1253", "The Visual in Anthropology: Documentary Films and Society"],
  ["ANTH 1300", "Anthropology of Addictions and Recovery"],
  ["ANTH 1301", "Anthropology of Homelessness"],
  ["ANTH 1622", "Archaeology of Settler Colonialism"],
  ["ANTH 1623", "Archaeology of Death"],
  ["ANTH 1720", "The Human Skeleton"],
  [
    "ANTH 1820",
    "Lost Languages: The Decipherment and Study of Ancient Writing Systems",
  ],
  ["ANTH 1830", "The Pictured Text"],
  ["ANTH 1848", "Ethnography + Social Critique"],
  ["ANTH 1901", "Anthropology in/of the Museum"],
  ["ANTH 1911", "Gender and Sexuality in the Middle East"],
  ["ANTH 1940", "Ethnographic Research Methods"],
  ["ANTH 2045", "Proposal Writing Workshop for Anthropological Fieldwork"],
  ["ANTH 2060", "Anthropology Dissertators' Seminar"],
  ["ANTH 2202", "Advanced GIS and Spatial Analysis"],
  ["ANTH 2271", "Fiction / Ethnography (+ the space between)"],
  ["ANTH 1970", "Individual Research Project"],
  ["ANTH 1990", "Senior Seminar: (Re)Making Anthropology"],
  [
    "ANTH 2320",
    "Anthropology and Development: Critical Ethnographic Perspectives",
  ],
  ["ANTH 2450", "Exchange Scholar Program"],
  ["ANTH 2970", "Preliminary Examination Preparation"],
  ["ANTH 2980", "Reading and Research"],
  ["ANTH 2990", "Thesis Preparation"],
  ["APMA 0160", "Introduction to Computing Sciences"],
  ["APMA 0200", "Introduction to Modelling"],
  ["APMA 0340", "Methods of Applied Mathematics II"],
  ["APMA 0350", "Applied Ordinary Differential Equations"],
  ["APMA 0360", "Applied Partial Differential Equations I"],
  ["APMA 0650", "Essential Statistics"],
  ["APMA 1160", "An Introduction to Numerical Optimization"],
  ["APMA 1180", "Introduction to Numerical Solution of Differential Equations"],
  ["APMA 1200", "Operations Analysis: Probabilistic Models"],
  ["APMA 1210", "Operations Research: Deterministic Models"],
  ["APMA 1330", "Applied Partial Differential Equations II"],
  ["APMA 1360", "Applied Dynamical Systems"],
  ["APMA 1650", "Statistical Inference I"],
  ["APMA 1655", "Honors Statistical Inference I"],
  ["APMA 1660", "Statistical Inference II"],
  ["APMA 1710", "Information Theory"],
  ["APMA 1860", "Graphs and Networks"],
  ["APMA 1910", "Race and Gender in the Scientific Community"],
  [
    "APMA 1930V",
    "Randomized Algorithms for Counting, Integration and Optimization",
  ],
  ["APMA 1941D", "Pattern Theory"],
  ["APMA 1970", "Independent Study"],
  ["APMA 1971", "Independent Study - WRIT"],
  ["APMA 2190", "Nonlinear Dynamical Systems I"],
  ["APMA 2230", "Partial Differential Equations I"],
  ["APMA 2240", "Partial Differential Equations"],
  ["APMA 2450", "Exchange Scholar Program"],
  ["APMA 2630", "Theory of Probability I"],
  ["APMA 2640", "Theory of Probability II"],
  ["APMA 2812D", "Topics in Modern Learning Theory and its Applications"],
  ["APMA 2822E", "Topic Course in Kinetic Theory"],
  ["APMA 2980", "Research in Applied Mathematics"],
  ["APMA 2990", "Thesis Preparation"],
  ["ARCH 0100", "Field Archaeology in the Ancient World"],
  [
    "ARCH 0230",
    "Myriad Mediterraneans: Archaeology, Representation and Decolonization",
  ],
  ["ARCH 0520", "Roman Archaeology and Art"],
  ["ARCH 1130", "A Burglar's Guide to Rome"],
  ["ARCH 1635", "The Great Heresy: Egypt in the Amarna Period"],
  [
    "ARCH 1765",
    "Pandemics, Pathogens, and Plagues in the Greek and Roman Worlds",
  ],
  ["ARCH 1900", "The Archaeology of College Hill"],
  ["ARCH 1970", "Individual Study Project in Old World Archaeology and Art"],
  ["ARCH 1990", "Senior Honors Thesis in Archaeology and the Ancient World"],
  ["ARCH 2153", "Archaeological Ethnography: A Multi-Temporal Contact Zone"],
  ["BIOL 0030", "Principles of Nutrition"],
  ["BIOL 0040", "Nutrition for Fitness and Physical Activity"],
  ["BIOL 0080", "Biotechnology Management"],
  ["ARCH 2950", "Intensive Readings in Ancient Language for Archaeologists"],
  ["ARCH 2980", "Individual Reading"],
  ["ARCH 2981", "Thesis Research"],
  ["ARCH 2982", "Individual Reading for Dissertation"],
  ["ARCH 2983", "Dissertation Research"],
  ["ARCH 2990", "Thesis Preparation"],
  ["BIOL 0100", "Living Biology at Brown and Beyond"],
  [
    "BIOL 0150D",
    "Techniques in Regenerative Medicine: Cells, Scaffolds and Staining",
  ],
  ["BIOL 0160", "Plants, Food, and People"],
  ["BIOL 0170", "Biotechnology in Medicine"],
  ["BIOL 0190F", "Darwinian Medicine"],
  ["BIOL 0210", "Diversity of Life"],
  ["BIOL 0280", "Biochemistry"],
  [
    "BIOL 0190P",
    "Pride and Prejudice in the Development of Scientific Theories",
  ],
  ["BIOL 0190R", "Phage Hunters, Part I"],
  ["BIOL 0190S", "Phage Hunters, Part II"],
  ["BIOL 0200", "The Foundation of Living Systems"],
  ["BIOL 0410", "Invertebrate Zoology"],
  ["BIOL 0420", "Principles of Ecology"],
  ["BIOL 0430", "The Evolution of Plant Diversity"],
  ["BIOL 0450", "Evolutionary Behavioral Ecology"],
  ["BIOL 0470", "Genetics"],
  ["BIOL 0480", "Evolutionary Biology"],
  ["BIOL 0495", "Statistical Analysis of Biological Data"],
  ["BIOL 0500", "Cell and Molecular Biology"],
  ["BIOL 0510", "Introductory Microbiology"],
  ["BIOL 0530", "Principles of Immunology"],
  ["BIOL 0600", "Genetic Screening in Model Organisms"],
  ["BIOL 0800", "Principles of Physiology"],
  ["BIOL 0940A", "Viral Epidemics"],
  [
    "BIOL 0940D",
    "Rhode Island Flora: Understanding and Documenting Local Plant Diversity",
  ],
  [
    "BIOL 0940G",
    "Antibiotic Drug Discovery: Identifying Novel Soil Microbes to Combat Antibiotic Resistance",
  ],
  ["BIOL 0960", "Independent Study in Science Writing"],
  ["BIOL 1040", "Ultrastructure/Bioimaging"],
  ["BIOL 1050", "Biology of the Eukaryotic Cell"],
  ["BIOL 1070", "Biotechnology and Global Health"],
  ["BIOL 1090", "Polymer Science for Biomaterials"],
  ["BIOL 1100", "Cell Physiology and Biophysics"],
  ["BIOL 1110", "Topics in Signal Transduction"],
  ["BIOL 1120", "Biomaterials"],
  ["BIOL 1140", "Tissue Engineering"],
  ["BIOL 1150", "Stem Cell Engineering"],
  ["BIOL 1160", "Principles of Exercise Physiology"],
  ["BIOL 1222A", "Current Topics in Functional Genomics"],
  ["BIOL 1260", "Physiological Pharmacology"],
  ["BIOL 1270", "Advanced Biochemistry"],
  ["BIOL 1290", "Cancer Biology"],
  ["BIOL 1300", "Biomolecular Interactions: Health, Disease and Drug Design"],
  ["BIOL 1330", "Biology of Reproduction"],
  ["BIOL 1420", "Experimental Design in Ecology"],
  ["BIOL 1430", "Population Genetics"],
  ["BIOL 1450", "Community Ecology"],
  ["BIOL 1465", "Human Population Genomics"],
  ["BIOL 1470", "Conservation Biology"],
  [
    "BIOL 1480",
    "Terrestrial Biogeochemistry and the Functioning of Ecosystems",
  ],
  ["BIOL 1540", "Molecular Genetics"],
  ["BIOL 1545", "Human Genetics and Genomics"],
  ["BIOL 1550", "Biology of Emerging Microbial Diseases"],
  ["BIOL 1560", "Virology"],
  ["BIOL 1565", "Survey of Biomedical Informatics"],
  ["BIOL 1575", "Evaluation of Health Information Systems"],
  ["BIOL 1800", "Animal Locomotion"],
  ["BIOL 1810", "21st Century Applications in Cell and Molecular Biology"],
  ["BIOL 1820", "Environmental Health and Disease"],
  ["BIOL 1865", "Toxicology"],
  ["BIOL 1970A", "Stem Cell Biology"],
  ["BIOL 2018", "Management Strategies in Biotechnology"],
  ["BIOL 1950", "Directed Research/Independent Study"],
  ["BIOL 1960", "Directed Research/Independent Study"],
  ["BIOL 2020", "Biotechnology Science and Industry"],
  ["BIOL 2040", "Ultrastructure/Bioimaging"],
  ["BIOL 2075", "Evaluation of Health Information Systems"],
  ["BIOL 2089", "The Importance of Intellectual Property in Biotechnology"],
  ["BIOL 2145", "Molecular Targets of Drug Discovery"],
  ["BIOL 2150", "Scientific Communication"],
  ["BIOL 2180", "Experiential Learning Industry, ELI"],
  ["BIOL 2222B", "Current Topics in Functional Genomics"],
  ["BIOL 2167", "In Vitro Models for Disease"],
  ["BIOL 2170", "Molecular Pharmacology and Physiology"],
  ["BIOL 2245", "Blood Substitutes: Principles and Therapeutics Development"],
  ["BIOL 2260", "Physiological Pharmacology"],
  ["BIOL 2270", "Advanced Biochemistry"],
  ["BIOL 2300", "Biomolecular Interactions: Health, Disease, and Drug Design"],
  ["BIOL 2340", "Neurogenetics and Disease"],
  ["BIOL 2350", "The Biology of Aging"],
  [
    "BIOL 2528",
    "Innovation and Commercialization in Medical Devices, Diagnostics, and Wearables",
  ],
  ["BIOL 2540", "Molecular Genetics"],
  ["BIOL 2545", "Human Genetics and Genomics"],
  ["BIOL 2560", "Advanced Virology"],
  ["BIOL 2640A", "Viral Immunology"],
  ["BIOL 2450", "Exchange Scholar Program"],
  ["BIOL 2860", "Molecular Mechanisms of Disease"],
  ["BIOL 2865", "Toxicology"],
  ["BIOL 2970", "Preliminary Examination Preparation"],
  ["BIOL 2980", "Graduate Independent Study"],
  ["BIOL 2985", "Graduate Seminar"],
  ["BIOL 2990", "Thesis Preparation"],
  ["BIOL 2995", "Thesis"],
  ["BIOL XLIST", "Courses of Interest to Biology Concentrators"],
  ["NEUR 1540", "Neurobiology of Learning and Memory"],
  ["NEUR 1560", "Developmental Neurobiology"],
  ["NEUR 1680", "Computational Neuroscience"],
  [
    "NEUR 1740",
    "The Diseased Brain: Mechanisms of Neurological and Psychiatric Disorders",
  ],
  ["NEUR 1930L", "Neurobiology of Love"],
  ["NEUR 1030", "Neural Systems"],
  ["NEUR 1930N", "Region of Interest: Amygdala"],
  ["NEUR 1970", "Independent Study"],
  ["NEUR 2970", "Preliminary Examination Preparation"],
  ["NEUR 2980", "Graduate Independent Study"],
  ["NEUR 2990", "Thesis Preparation"],
  ["MED 2980", "Independent Study in Population Medicine"],
  ["PLME 0400", "Introduction to Medical Illustration"],
  ["BEO 1930A", "BEO Capstone I: Organizational Studies Track"],
  [
    "BEO 1930B",
    "BEO Capstone I: Entrepreneurship and Technology Management Track",
  ],
  [
    "BEO 1940B",
    "BEO Capstone II: Entrepreneurship and Technology Management Track",
  ],
  ["BEO 1970", "Independent Study"],
  ["CHEM 0100", "Introductory Chemistry"],
  ["CHEM 0350", "Organic Chemistry"],
  ["CHEM 0360", "Organic Chemistry"],
  ["CHEM 0400", "Biophysical and Bioinorganic Chemistry"],
  ["CHEM 0500", "Inorganic Chemistry"],
  ["Students MUST register for a lecture section and a lab", undefined],
  ["CHEM 0970", "Undergraduate Research"],
  ["CHEM 0980", "Undergraduate Research"],
  [
    "CHEM 0980S",
    "Undergraduate Research - Writing Designated and Mandatory S/NC",
  ],
  ["CHEM 0999", "Chemistry and Art"],
  ["CHEM 1060", "Advanced Inorganic Chemistry"],
  ["CHEM 1140", "Physical Chemistry: Quantum Chemistry"],
  ["CHEM 1150", "Physical Chemistry: Thermodynamics and Statistical Mechanics"],
  ["CHEM 1160", "Physical Chemistry Laboratory"],
  ["CHEM 1230", "Chemical Biology"],
  ["CHEM 1240", "Biochemistry"],
  ["CHEM 1450", "Advanced Organic Chemistry"],
  ["CHEM 1560G", "Nuclear Magnetic Resonance"],
  ["CHEM 1560N", "Organometallic Chemistry"],
  ["CHEM 1560Q", "Accelerating Chemical Discovery"],
  ["CHEM 2010", "Advanced Thermodynamics"],
  ["CHEM 2020", "Statistical Mechanics"],
  ["CHEM 2310", "Organometallic Chemistry"],
  ["CHEM 2320", "Solid State Chemistry"],
  ["CHEM 2410", "Organic Mechanisms"],
  ["CHEM 2420", "Organic Reactions"],
  ["CHEM 2430", "Synthetic Organic Chemistry"],
  ["CHEM 2770", "Quantum Mechanics"],
  ["CHEM 2780", "Quantum Mechanics"],
  ["CHEM 2870", "Departmental Colloquia"],
  ["CHEM 2970", "Preliminary Examination Preparation"],
  ["CHEM 2980", "Research"],
  ["CHEM 2981", "Research"],
  ["CHEM 2990", "Thesis Preparation"],
  ["CHEM XLIST", "Courses of Interest to Students wishing to Study Chemistry"],
  [
    "CLAS 0210R",
    "Revolutionary Classics (or, the classical origins of your Brown education)",
  ],
  ["CLAS 0320", "21st century Classics"],
  ["CLAS 0855", "The Bhagavad G#t#"],
  ["CLAS 0900", "Greek Mythology"],
  ["CLAS 0930", "Ghost, Apparitions and the Supernatural in Greece and Rome"],
  ["CLAS 1120G", "The Idea of Self"],
  ["CLAS 1120W", "Aristotle"],
  [
    "CLAS 1220",
    "The Fall of Empires and Rise of Kings: Greek History 478 to 323 BC",
  ],
  ["CLAS 1230", "The Persian Empire and Achaemenid Culture"],
  ["CLAS 1310", "Roman History I: The Rise and Fall of an Imperial Republic"],
  ["CLAS 1420", "Death in the West"],
  ["CLAS 1750H", "Heroes and Heroism in Graeco - Roman Antiquity and Beyond"],
  [
    "CLAS 1930H",
    "&quot;The Battle of the Books&quot;: The Quarrel between the Ancients and the Moderns",
  ],
  ["CLAS 1970", "Special Topics"],
  ["CLAS 1990", "Conference: Especially for Honors Students"],
  ["CLAS 2110E", "Medeas in America"],
  ["CLAS 2450", "Exchange Scholar Program"],
  ["CLAS 2970", "Preliminary Examination Preparation"],
  ["CLAS 2980", "Reading and Research"],
  ["CLAS 2990", "Thesis Preparation"],
  ["CLAS XLIST", "Courses of Interest to Classics Concentrators"],
  ["GREK 0110", "Intensive Introduction to Ancient Greek"],
  ["GREK 0200", "Essentials of the Greek Language"],
  ["GREK 0300", "Introduction to Greek Literature"],
  ["GREK 0400", "Introduction to Greek Literature"],
  ["GREK 1111H", "Hellenistic Literature"],
  ["GREK 1111J", "Hippocratic Medicine"],
  ["GREK 1140", "Introduction to Greek Linguistics"],
  ["GREK 1820", "Greek Literature Survey after 450 BCE"],
  ["GREK 1910", "Special Topics"],
  ["GREK 1990", "Conference: Especially for Honors Students"],
  [
    "GREK 2110G",
    "Political Trials: Treason and Accountability in Fourth Century Athens",
  ],
  ["GREK 2970", "Preliminary Exam Preparation"],
  ["GREK 2980", "Reading and Research"],
  ["GREK 2990", "Thesis Preparation"],
  ["LATN 0100", "Essentials of the Latin Language"],
  ["LATN 0110", "Intensive Introduction to Latin"],
  ["LATN 0200", "Essentials of the Latin Language"],
  ["LATN 0300", "Introduction to Latin Literature"],
  ["LATN 1110I", "Lucretius"],
  ["LATN 1110R", "Catilines: Cicero and Sallust"],
  ["LATN 1120D", "Alcuin"],
  ["LATN 1150", "Latin Prose Composition"],
  ["LATN 1810", "Survey of Republican Literature"],
  ["LATN 0400", "Introduction to Latin Literature"],
  ["LATN 1060G", "Tacitus"],
  ["LATN 1970", "Special Topics"],
  ["LATN 1990", "Conference: Especially for Honors Students"],
  ["LATN 2970", "Preliminary Exam Preparation"],
  ["LATN 2980", "Reading and Research"],
  ["LATN 2990", "Thesis Preparation"],
  ["MGRK 0100", "Introduction to Modern Greek"],
  ["MGRK 0300", "Intermediate Modern Greek"],
  ["MGRK 0600", "Advanced Modern Greek"],
  ["SANS 0200", "Elementary Sanskrit II"],
  ["SANS 1500", "Sanskrit Song and Music"],
  ["SANS 1970", "Independent Study - Special Topics"],
  ["SANS 2970", "Sanskrit Preliminary Exam Preparation"],
  [
    "MGRK 1210",
    "A Migration Crisis? Displacement, Materiality, and Experience",
  ],
  ["MGRK 1800", "In Other Words: Translating Greece"],
  ["SANS 0100", "Elementary Sanskrit I"],
  ["SANS 2980", "Sanskrit Reading and Research"],
  ["CLPS 0010", "Mind, Brain and Behavior: An Interdisciplinary Approach"],
  ["CLPS 0100", "Learning and Conditioning"],
  ["CLPS 0110", "Animal Behavior"],
  ["CLPS 0200", "Human Cognition"],
  ["CLPS 0220", "Making Decisions"],
  ["CLPS 0300", "Introduction to Linguistics"],
  ["CLPS 0450", "Brain Damage and the Mind"],
  ["CLPS 0500", "Perception and Mind"],
  [
    "CLPS 0540",
    "Simulating Reality: The (Curious) History and Science of Immersive Experiences",
  ],
  ["CLPS 0550", "Science of Consciousness"],
  ["CLPS 0610", "Children's Thinking: The Nature of Cognitive Development"],
  ["CLPS 0701", "Personality"],
  ["CLPS 0900", "Statistical Methods"],
  ["CLPS 0950", "Introduction to programming"],
  ["CLPS 1150", "Memory and the Brain"],
  ["CLPS 1195", "Life Under Water in the Anthropocene"],
  ["CLPS 1250", "Human Factors"],
  ["CLPS 1280B", "Special Topics in Cognition: Collective Cognition"],
  ["CLPS 1341", "Lexical Semantics"],
  ["CLPS 1361", "Information Theory in Language"],
  ["CLPS 1420", "Cognitive Neuropsychology"],
  ["CLPS 1480B", "Cognitive Aging and Dementia"],
  ["CLPS 1310", "Phonology"],
  ["CLPS 1330", "Introduction to Syntax"],
  ["CLPS 1480H", "Disorders of Memory"],
  ["CLPS 1492", "Computational Cognitive Neuroscience"],
  ["CLPS 1500", "Perception and Action"],
  ["CLPS 1510", "Laboratory in Auditory Perception"],
  ["CLPS 1570", "Perceptual Learning"],
  ["CLPS 1580C", "Visualizing Information"],
  [
    "CLPS 1591",
    "Experimental Analysis of Vision for Action and Vision for Perception: Are There Separate Mechanisms?",
  ],
  ["CLPS 1610", "Cognitive Development"],
  ["CLPS 1660", "Learning Compositional Language"],
  [
    "CLPS 1680F",
    "Topics in Development: The Developmental and Evolutionary Origins of Mind",
  ],
  ["CLPS 1700", "Abnormal Psychology"],
  ["CLPS 1730", "Psychology in Business and Economics"],
  ["CLPS 1760", "The Moral Brain"],
  ["CLPS 1770", "Stigma and Prejudice"],
  [
    "CLPS 1782",
    "Me, Myself, and I: Exploring Senses of Self from a Multidisciplinary Perspective (COST 1082)",
  ],
  ["CLPS 1791", "Laboratory in Social Cognition"],
  ["CLPS 1800", "Language Processing"],
  ["CLPS 1900", "Research Methods And Design"],
  ["CLPS 1960", "Senior Seminar in Behavioral Decision Sciences"],
  [
    "CLPS 1970",
    "Directed Reading in Cognitive, Linguistic and Psychological Sciences",
  ],
  [
    "CLPS 1980",
    "Directed Research in Cognitive, Linguistic and Psychological Sciences",
  ],
  ["CLPS 2001", "Core Concepts in Cognitive and Psychological Sciences I"],
  ["CLPS 2091", "Graduate First Year Project Research"],
  ["CLPS 2092", "Graduate First Year Project Research"],
  ["CLPS 2095", "Practicum in Teaching"],
  ["CLPS 2096", "Directed Graduate Research"],
  ["CLPS 2450", "Exchange Scholar Program"],
  ["CLPS 2990", "Thesis Preparation"],
  ["LING XLIST", "Courses of Interest to Concentrators in Linguistics"],
  [
    "HMAN 1971S",
    "Introduction to iPhone/iPad Moviemaking Using 3-D and 360 VR Comparisons",
  ],
  ["HMAN 1974S", "The Costs of Climate Change"],
  ["HMAN 1975F", "Censorship and the Arts"],
  [
    "HMAN 1975G",
    "Planning the Family: Gender, Reproduction, and the Politics of Choice.",
  ],
  ["HMAN 1990", "Independent Study"],
  ["HMAN 2401G", "Frameworks of Antiquity: Disciplines, Discourses, Politics"],
  [
    "HMAN 2401H",
    "Global Histories of Psychiatry and Anti-Psychiatry since 1945",
  ],
  ["HMAN 2401J", "The Art of Refusal"],
  ["HMAN 2500", "Project Development Workshop"],
  ["COLT 0510K", "The 1001 Nights"],
  ["COLT 0610D", "Rites of Passage"],
  ["COLT 0610Q", "Before Wikipedia"],
  [
    "COLT 0710N",
    "A Comparative Introduction to the Literatures of the Americas",
  ],
  ["COLT 0710X", "Fan Fiction"],
  ["COLT 0710Z", "Comedy from Athens to Hollywood"],
  ["COLT 0711Q", "Writing Love in Korean Literature"],
  ["COLT 0810H", "How Not to Be a Hero"],
  ["COLT 0810L", "The Pursuit of Happiness"],
  ["COLT 1440U", "The Listener (Literature, Theory, Film)"],
  ["COLT 1210", "Introduction to the Theory of Literature"],
  [
    "COLT 1420F",
    "Fantastic and Existentialist Literatures of Argentina, Uruguay and Brazil",
  ],
  ["COLT 1420O", "Proust, Joyce and Faulkner"],
  ["COLT 1430B", "Art and Exemplarity in Medieval and Early Modern Literature"],
  ["COLT 1710C", "Literary Translation Workshop"],
  ["COLT 1810P", "Literature and Medicine"],
  ["COLT 1814U", "Politics of Reading"],
  ["COLT 1970", "Individual Independent Study"],
  ["COLT 1980", "Group Independent Study"],
  ["COLT 1990", "Senior Thesis Preparation"],
  ["COLT 2450", "Exchange Scholar Program"],
  ["CSCI 0081", "TA Apprenticeship: Full Credit"],
  ["COLT 2720D", "Translation: Theory and Practice"],
  ["COLT 2820A", "New Directions for Comparative Literature"],
  ["COLT 2830B", "Frameworks of Antiquity: Disciplines, Discourses, Politics"],
  ["COLT 2980", "Reading and Research"],
  ["COLT 2990", "Thesis Preparation"],
  ["CSCI 0020", "The Digital World"],
  ["CSCI 0082", "TA Apprenticeship: Half Credit"],
  ["CSCI 0100", "Data Fluency for All"],
  ["CSCI 0111", "Computing Foundations: Data"],
  [
    "CSCI 0150",
    "Introduction to Object-Oriented Programming and Computer Science",
  ],
  ["CSCI 0190", "Accelerated Introduction to Computer Science"],
  ["CSCI 0320", "Introduction to Software Engineering"],
  ["CSCI 0330", "Introduction to Computer Systems"],
  ["CSCI 1010", "Theory of Computation"],
  ["CSCI 1230", "Introduction to Computer Graphics"],
  ["CSCI 1234", "Computer Graphics Lab"],
  ["CSCI 1250", "Introduction to Computer Animation"],
  ["CSCI 1270", "Database Management Systems"],
  ["CSCI 1330", "Computer Systems"],
  ["CSCI 1370", "Virtual Reality Design for Science"],
  ["CSCI 1570", "Design and Analysis of Algorithms"],
  ["CSCI 1410", "Artificial Intelligence"],
  ["CSCI 1430", "Computer Vision"],
  [
    "CSCI 1450",
    "Advanced Introduction to Probability for Computing and Data Science",
  ],
  ["CSCI 1470", "Deep Learning"],
  ["CSCI 1650", "Software Security and Exploitation"],
  ["CSCI 1760", "Multiprocessor Synchronization"],
  ["CSCI 1805", "Computers, Freedom and Privacy"],
  ["CSCI 1810", "Computational Molecular Biology"],
  ["CSCI 1870", "Cybersecurity Ethics"],
  ["CSCI 1950N", "2D Game Engines"],
  ["CSCI 1951C", "Designing Humanity Centered Robots"],
  ["CSCI 1971", "Independent Study in 2D Game Engines"],
  ["CSCI 1972", "Topics in 3D Game Engine Development"],
  ["CSCI 1973", "Independent Study"],
  ["CSCI 2450", "Exchange Scholar Program"],
  ["CSCI 2890", "Comprehensive Examination Preparation"],
  [
    "CSCI 1951V",
    "Hypertext/Hypermedia Seminar: The Web Was Not the Beginning and the Web Is Not the End",
  ],
  ["CSCI 1970", "Individual Independent Study"],
  ["CSCI 2951F", "Learning and Sequential Decision Making"],
  ["CSCI 2980", "Reading and Research"],
  ["CSCI 2990", "Thesis Preparation"],
  ["CSCI XLIST", "Courses of Interest to Concentrators in Computer Science"],
  ["ERLY 1990", "Thesis Preparation"],
  ["CHIN 0100", "Basic Chinese"],
  ["CHIN 0200", "Basic Chinese"],
  ["CHIN 0300", "Intermediate Chinese"],
  ["CHIN 0350", "Elementary to Intermediate Chinese for Advanced Beginners"],
  ["CHIN 0400", "Intermediate Chinese"],
  ["CHIN 0450", "Advanced Chinese for Heritage Learners"],
  ["CHIN 0500", "Advanced Modern Chinese I"],
  ["CHIN 0600", "Advanced Modern Chinese I"],
  ["CHIN 0700", "Advanced Modern Chinese II"],
  ["CHIN 0800", "Advanced Modern Chinese II"],
  ["CHIN 0920D", "Business Chinese"],
  ["CHIN 1040", "Modern Chinese Literature"],
  ["CHIN 1910", "Independent Study"],
  ["CHIN 2450", "Exchange Scholar Program"],
  [
    "EAST 0407",
    "Yo no naka: The Poetics of Fiction and Virtual Reality in Premodern Japan",
  ],
  ["EAST 1100", "Korean Culture and Film"],
  [
    "EAST 1270",
    "China Through the Lens: History, Cinema, and Critical Discourse",
  ],
  [
    "EAST 1290",
    "The Korea “Brand”: Understanding KPop, Film, and Culture of the Two Koreas in the Global Context",
  ],
  ["EAST 1310", "Silk Road Fictions"],
  ["EAST 1910", "Independent Study"],
  ["EAST 1930", "Reading and Writing of the Honors Thesis"],
  ["EAST 1936", "Memory and Justice in East Asia"],
  ["EAST 1940", "Reading and Writing of the Honors Thesis"],
  ["EAST 2450", "Exchange Scholar Program"],
  ["EAST XLIST", "Courses of Interest to Concentrators"],
  ["JAPN 0100", "Basic Japanese"],
  ["JAPN 0200", "Basic Japanese"],
  ["JAPN 0300", "Intermediate Japanese"],
  ["JAPN 0400", "Intermediate Japanese"],
  ["JAPN 0500", "Advanced Japanese I"],
  ["JAPN 0600", "Advanced Japanese I"],
  ["JAPN 0700", "Advanced Japanese II"],
  ["JAPN 0800", "Advanced Japanese II"],
  ["JAPN 1010", "Readings in Contemporary Japanese Fiction"],
  ["KREA 0100", "Korean"],
  ["KREA 0200", "Korean"],
  ["JAPN 1310", "Japanese Linguistics: Communication an"],
  ["KREA 0300", "Intermediate Korean"],
  ["JAPN 1910", "Independent Study"],
  ["KREA 0400", "Intermediate Korean"],
  ["KREA 0500", "Advanced Korean"],
  ["KREA 0600", "Advanced Korean"],
  ["KREA 1090", "Translating Korean: Fiction, Poetry &amp; Film"],
  ["KREA 1910", "Independent Study"],
  ["EEPS 0010", "Face of the Earth"],
  ["EEPS 0050", "Mars, Moon, and the Earth"],
  ["EEPS 0070", "Introduction to Oceanography"],
  ["EEPS 0160I", "Diamonds"],
  ["EEPS 0220", "Earth Processes"],
  ["EEPS 0230", "Geochemistry: Earth and Planetary Materials and Processes"],
  ["EEPS 0240", "Earth: Evolution of a Habitable Planet"],
  ["EEPS 0350", "Mathematical Methods of Fluid"],
  ["EEPS 0810", "Planetary Geology"],
  ["EEPS 1120", "Paleoceanography"],
  ["EEPS 1240", "Stratigraphy and Sedimentation"],
  ["EEPS 1330", "Global Environmental Remote Sensing"],
  ["EEPS 1410", "Mineralogy"],
  ["EEPS 1420", "Petrology"],
  ["EEPS 1560", "Global Tectonics"],
  ["EEPS 1610", "Solid Earth Geophysics"],
  ["EEPS 1615", "The Environmental Policy Process"],
  ["EEPS 1630", "Introduction to Quantitative Glaciology"],
  [
    "EEPS 1960G",
    "Earth Science Curriculum Design and Teaching Practicum for Elementary School",
  ],
  ["EEPS 1960H", "The Early Earth"],
  ["EEPS 1970", "Individual Study of Geologic Problems"],
  ["EEPS 2300", "Mathematical and Computational Earth Sciences"],
  ["EEPS 2450", "Exchange Scholar Program"],
  ["EEPS 2910Z", "Trace Element Geochemistry"],
  ["EEPS 2980", "Research in Geological Sciences"],
  ["EEPS 2990", "Thesis Preparation"],
  ["ECON 0110", "Principles of Economics"],
  ["ECON 0170", "Essential Mathematics for Economics"],
  ["ECON 0200", "20th Century Political Economy"],
  ["ECON 0710", "Financial Accounting"],
  ["ECON 1070", "Race, Crime, and Punishment in America"],
  ["ECON 1090", "Introduction to Game Theory"],
  ["ECON 1110", "Intermediate Microeconomics"],
  ["ECON 1200", "History of Economic Thought"],
  ["ECON 1210", "Intermediate Macroeconomics"],
  [
    "ECON 1225",
    "Advanced Macroeconomics: Monetary, Fiscal, and Stabilization Policies",
  ],
  ["ECON 1255", "Unemployment: Models and Policies"],
  ["ECON 1310", "Labor Economics"],
  ["ECON 1340", "Economics of Global Warming"],
  ["ECON 1350", "Environmental Economics and Policy"],
  ["ECON 1360", "Health Economics"],
  ["ECON 1370", "Race and Inequality in the United States"],
  [
    "ECON 1390",
    "Inequality of Income, Wealth, and Health in the United States",
  ],
  ["ECON 1400", "The Economics of Mass Media"],
  ["ECON 1410", "Urban Economics"],
  ["ECON 1420", "Industrial Organization"],
  ["ECON 1440", "The Economic Analysis of Political Behavior"],
  ["ECON 1470", "Bargaining Theory and Applications"],
  ["ECON 1530", "Health, Hunger and the Household in Developing Countries"],
  ["ECON 1540", "International Trade"],
  ["ECON 1550", "International Finance"],
  ["ECON 1560", "Economic Growth"],
  ["ECON 1570", "The Economics of Latin Americans"],
  ["ECON 1590", "The Economy of China since 1949"],
  ["ECON 1620", "Introduction to Econometrics"],
  ["ECON 1629", "Applied Research Methods for Economists"],
  ["ECON 1630", "Mathematical Econometrics I"],
  ["ECON 1640", "Mathematical Econometrics II"],
  ["ECON 1710", "Investments I"],
  ["ECON 1720", "Corporate Finance"],
  ["ECON 1750", "Investments II"],
  ["ECON 1760", "Financial Institutions"],
  ["ECON 1780", "Advanced Topics in Corporate Finance"],
  ["ECON 1805", "Economics in the Laboratory"],
  ["ECON 1820", "Theory of Behavioral Economics"],
  ["ECON 1830", "Behavioral Finance"],
  ["ECON 1850", "Theory of Economic Growth"],
  ["ECON 1970", "Independent Research"],
  ["ECON 2010", "Mathematics for Economists"],
  ["ECON 2020", "Applied Economics Analysis"],
  ["ECON 2030", "Introduction to Econometrics I"],
  ["ECON 2040", "Econometric Methods"],
  ["ECON 2050", "Microeconomics I"],
  ["ECON 2060", "Microeconomics II"],
  ["ECON 2070", "Macroeconomics I"],
  ["ECON 2080", "Macroeconomics II"],
  ["ECON 2140", "Economic Modeling for Applied Economists"],
  ["ECON 2150", "Market Design"],
  ["ECON 2180", "Game Theory"],
  ["ECON 2260", "Political Economy I"],
  ["ECON 2270", "Political Economy II"],
  ["ECON 2310", "Labor Economics"],
  ["ECON 2330", "Topics in Labor Economics"],
  ["ECON 2350", "Inequality and Social Policy"],
  ["ECON 2410", "Urbanization"],
  ["ECON 2450", "Exchange Scholar Program"],
  ["ECON 2470", "Industrial Organization"],
  ["ECON 2510", "Economic Development I"],
  ["ECON 2520", "Economic Development II"],
  ["ECON 2530", "Behavioral and Experimental Economics"],
  ["ECON 2630", "Econometric Theory"],
  ["ECON 2800", "Macroeconomic Slack"],
  ["ECON 2860", "Comparative Development"],
  ["EDUC 1900", "Senior Seminar"],
  ["ECON 2890C", "Topics in Macro and Monetary Economics"],
  ["ECON 2980", "Reading and Research"],
  ["ECON 2990", "Thesis Preparation"],
  [
    "EDUC 0300",
    "Introduction to Education and Society: Foundations of Opportunity and Inequality",
  ],
  ["EDUC 1970", "Independent Study"],
  ["EDUC 1990", "Independent Reading and Research"],
  ["EDUC 1991", "Independent Reading and Research"],
  ["EDUC 2450", "Exchange Scholar Program"],
  ["EDUC 2990", "Thesis Preparation"],
  ["EDUC XLIST", "Courses of Interest to Concentrators in Education"],
  ["ASYR 2120", "Historiography of Exact Sciences"],
  ["ASYR 2800", "Archaeologies of Text"],
  ["ASYR 2980", "Reading and Research"],
  ["ASYR 2990", "Thesis Preparation"],
  [
    "ASYR XLIST",
    "Courses of Interest to Concentrators in Egyptology and Assyriology",
  ],
  [
    "EGYT 1320",
    "Introduction to Classical Hieroglyphic Egyptian Writing and Language (Middle Egyptian II)",
  ],
  ["EGYT 1410", "Ancient Egyptian Literature"],
  ["EGYT 1910", "Senior Seminar"],
  ["EGYT 1920", "Senior Seminar"],
  ["EGYT 2300", "Readings in Ancient Egyptian"],
  ["EGYT 2450", "Exchange Scholar Program"],
  ["EGYT 2970", "Preliminary Examination Preparation"],
  ["EGYT 2980", "Reading and Research"],
  ["EGYT 2990", "Thesis Preparation"],
  [
    "EGYT XLIST",
    "Courses of Interest to Concentrators in Egyptology and Assyriology",
  ],
  ["EGYT 1430", "History of Egypt I"],
  ["ENGN 0032", "Introduction to Engineering: Design"],
  ["ENGN 0061", "Undergraduate Teaching Assistant Apprenticeship: Full Credit"],
  ["ENGN 0062", "Undergraduate Teaching Assistant Apprenticeship: Half Credit"],
  ["ENGN 0130", "The Engineer's Burden: Why Changing the World is Difficult"],
  ["ENGN 0260", "Mechanical Technology"],
  ["ENGN 0310", "Mechanics of Solids and Structures"],
  ["ENGN 0410", "Materials Science"],
  ["ENGN 0490", "Fundamentals of Environmental Engineering"],
  ["ENGN 0510", "Electricity and Magnetism"],
  ["ENGN 0720", "Thermodynamics"],
  ["ENGN 0810", "Fluid Mechanics"],
  ["ENGN 0900", "Managerial Decision Making"],
  ["ENGN 0930A", "Appropriate Technology"],
  ["ENGN 1000", "Projects in Engineering Design I"],
  ["ENGN 1010", "The Entrepreneurial Process"],
  ["ENGN 1230", "Instrumentation Design"],
  ["ENGN 1342", "Groundwater Flow and Transport"],
  ["ENGN 1410", "Physical Chemistry of Solids"],
  ["ENGN 1470", "Structure &amp; Properties of Nonmetallic Materials"],
  ["ENGN 1490", "Biomaterials"],
  ["ENGN 1510", "Nanoengineering and Nanomedicine"],
  ["ENGN 1520", "Cardiovascular Engineering"],
  ["ENGN 1570", "Linear System Analysis"],
  ["ENGN 1590", "Introduction to Semiconductors and Semiconductor Electronics"],
  ["ENGN 1630", "Digital Electronics Systems Design"],
  ["ENGN 1650", "Embedded Microprocessor Design"],
  ["ENGN 1690", "Photonics Devices and Sensors"],
  ["ENGN 1735", "Vibration of Mechanical Systems"],
  ["ENGN 1750", "Advanced Mechanics of Solids"],
  ["ENGN 1930L", "Biomedical Engineering Design and Innovation"],
  ["ENGN 1930M", "Industrial Design"],
  ["ENGN 1931D", "Design of Mechanical Assemblies"],
  ["ENGN 1931F", "Introduction to Power Engineering"],
  [
    "ENGN 1931J",
    "Social Impact of Emerging Technologies – The Role of Scientists and Engineers",
  ],
  ["ENGN 1931P", "Energy and the Environment"],
  ["ENGN 1931R", "The Chemistry of Environmental Pollution"],
  [
    "ENGN 1931T",
    "Entrepreneurship Practicum: Starting, Running, and Scaling Ventures",
  ],
  ["ENGN 1970", "Independent Studies in Engineering"],
  ["ENGN 1971", "Independent Study in Engineering"],
  ["ENGN 2125", "Engineering Management + Decision Making"],
  ["ENGN 2130", "Innovation and Technology Management"],
  ["ENGN 2140", "Innovation and Technology Management II"],
  [
    "ENGN 2180",
    "Globalization Immersion Experience and Entrepreneurship Laboratory",
  ],
  ["ENGN 2210", "Continuum Mechanics"],
  ["ENGN 2410", "Thermodynamics of Materials"],
  ["ENGN 2450", "Exchange Scholar Program"],
  ["ENGN 2530", "Digital Signal Processing"],
  ["ENGN 2620", "Solid State Quantum and Optoelectronics"],
  ["ENGN 2735", "Vibration of Mechanical Systems"],
  ["ENGN 2750", "Chemical Kinetics and Reactor Engineering"],
  ["ENGN 2810", "Fluid Mechanics I"],
  ["ENGN 2910S", "Cancer Nanotechnology"],
  [
    "ENGN 2911R",
    "Analytical Modeling for Biomechanical and Biomedical Systems",
  ],
  ["ENGN 2911T", "Ultrafast Optical Phenomena"],
  [
    "ENGN 2911V",
    "Advanced Topics in Computational Mechanics: Isogeometric Analysis, Meshfree Methods, and FSI",
  ],
  ["ENGN 2912B", "Scientific Programming in C++"],
  ["ENGN 2912J", "Asymptotic and Perturbation Methods"],
  ["ENGN 2912L", "Topics in Bioelectronics"],
  ["ENGN 2912T", "Experimental Fluid Mechanics"],
  ["ENGN 2970", "Preliminary Examination Preparation"],
  ["ENGN 2990", "Thesis Preparation"],
  ["ENGL 0100A", "How To Read A Poem"],
  ["ENGL 0100D", "Matters of Romance"],
  ["ENGL 0100F", "Devils, Demons, Do-Gooders"],
  ["ENGL 0100P", "Love Stories"],
  ["ENGL 0100V", "Inventing Asian American Literature"],
  ["ENGL 0100Y", "Do the Right Thing"],
  ["ENGL 0150S", "The Roaring Twenties"],
  ["ENGL 0150X", "The Claims of Fiction"],
  ["ENGL 0150Y", "Brontës and Brontëism"],
  ["ENGL 0151A", "Hitchcock!"],
  ["ENGL 0151C", "Midsummers"],
  ["ENGL 0151E", "Genres of American Comedy"],
  ["ENGL 0310A", "Shakespeare"],
  ["ENGL 0511H", "Late Romantics"],
  ["ENGL 0700E", "Postcolonial Literature"],
  ["ENGL 0700R", "Modernist Cities"],
  ["ENGL 0700U", "Modernism and Race"],
  ["ENGL 0710Q", "American Literature in the Era of Segregation"],
  ["ENGL 0710R", "Poetry and Science"],
  ["ENGL 0930", "Introduction to Creative Nonfiction"],
  ["ENGL 1030F", "The Artist in the Archives"],
  ["ENGL 1030H", "Black Popular Culture and Social Movements"],
  ["ENGL 1050A", "Narrative"],
  ["ENGL 1050B", "True Stories"],
  ["ENGL 1050P", "Reframing Race in Art Writing"],
  ["ENGL 1050Q", "Writing the Family"],
  ["ENGL 1050E", "Sportswriting"],
  ["ENGL 1140A", "Intellectual Pleasures: Reading/Writing the Literary Text"],
  ["ENGL 1050F", "Line Work: Experiments in Short-Form Writing"],
  ["ENGL 1050G", "Journalistic Writing"],
  ["ENGL 1050H", "Journalistic Writing"],
  ["ENGL 1140B", "The Public Intellectual"],
  ["ENGL 1140D", "Writing Diversity: A Workshop"],
  ["ENGL 1140E", "Writing for Activists"],
  ["ENGL 1160F", "Reporting Crime and Justice"],
  ["ENGL 1180M", "Special Delivery: Letters and Diaries"],
  ["ENGL 1180P", "Further Adventures in Creative Nonfiction"],
  ["ENGL 1180R", "Travel Writing: Personal and Cultural Narratives"],
  ["ENGL 1180V", "Contemporary Asian American Writers"],
  [
    "ENGL 1190M",
    "The Teaching and Practice of Writing: Writing Fellows Program",
  ],
  ["ENGL 1190U", "Nature Writing"],
  ["ENGL 1190X", "Nonfiction Now"],
  ["ENGL 1190Z", "The Art of Craft"],
  ["ENGL 1200", "Independent Study in Nonfiction Writing"],
  ["ENGL 1311G", "Shakespeare, Love and Friendship"],
  ["ENGL 1311N", "England and the Renaissance"],
  ["ENGL 1361F", "Spenser and Shakespeare"],
  ["ENGL 1361G", "Tolkien and the Renaissance"],
  ["ENGL 1361L", "Milton"],
  [
    "ENGL 1380",
    "Undergraduate Independent Study in Medieval and Early Modern Literatures",
  ],
  [
    "ENGL 1511P",
    "Realism, Modernism, Postmodernism: The American Novel and its Traditions",
  ],
  ["ENGL 1511Q", "Melville, Conrad, and the Sea"],
  ["ENGL 1561I", "The Nineteenth-Century Novel"],
  ["ENGL 1561Y", "In Excess: Rossetti, Hopkins, Wilde"],
  [
    "ENGL 1580",
    "Undergraduate Independent Study in the Enlightenment and the Rise of National Literatures",
  ],
  ["ENGL 1710I", "Harlem Renaissance: The Politics of Culture"],
  ["ENGL 1710J", "Modern African Literature"],
  [
    "ENGL 1710M",
    "Nationalizing Narratives: Race, Nationalism, and the American Novel",
  ],
  ["ENGL 1762M", "Caribbean Literature"],
  [
    "ENGL 1780",
    "Undergraduate Independent Study in Modern and Contemporary Literatures",
  ],
  [
    "ENGL 1900Y",
    "Medieval Manuscript Studies: Paleography, Codicology, and Interpretation",
  ],
  ["ENGL 1710P", "The Literature and Culture of Black Power Reconsidered"],
  ["ENGL 1762L", "City Spaces, City Memories"],
  ["ENGL 1900Z", "Neuroaesthetics and Reading"],
  ["ENGL 1901L", "Cronenberg/Lynch"],
  ["ENGL 1901M", "Reading Literature in an Information Age"],
  ["ENGL 1901N", "The Sublime"],
  ["ENGL 1901P", "Waves and Edges: Poetry and the Sea"],
  ["ENGL 1950F", "Law and Literature"],
  ["ENGL 1991", "Senior Honors Seminar in English"],
  ["ENGL 1992", "Senior Honors Thesis in English"],
  ["ENGL 1993", "Senior Honors Seminar in Nonfiction Writing"],
  [
    "ENGL 2380",
    "Graduate Independent Study in Medieval and Early Modern Literatures",
  ],
  ["ENGL 2450", "Exchange Scholar Program"],
  [
    "ENGL 2561V",
    "The Pursuit of Happiness: Transatlantic Literary Culture in the Long Eighteenth Century",
  ],
  [
    "ENGL 2580",
    "Graduate Independent Study in the Enlightenment and the Rise of National Literatures",
  ],
  [
    "ENGL 2780",
    "Graduate Independent Study in Modern and Contemporary Literatures",
  ],
  ["ENGL 2900X", "Postcolonial Theory"],
  ["ENGL 2901R", "Technologies of Memory"],
  ["ENGL 2950", "Seminar in Pedagogy and Composition Theory"],
  ["ENGL 2970", "Preliminary Examination Preparation"],
  ["ENGL 2990", "Thesis Preparation"],
  ["ENGL XLIST", "Courses of Interest to Students Concentrating in English"],
  ["ENVS 0070C", "Transcending Transportation Impacts"],
  [
    "ENVS 0110",
    "Humans, Nature, and the Environment: Addressing Environmental Change in the 21st Century",
  ],
  ["ENVS 0490", "Environmental Science in a Changing World"],
  ["ENVS 1105", "Introduction to Environmental GIS"],
  ["ENVS 1350", "Environmental Economics and Policy"],
  ["ENVS 1421", "Podcasting For the Common Good: Storytelling with Science"],
  ["ENVS 1490", "SES-Independent Study/Science Writing"],
  ["ENVS 1491", "SES-Terrestrial Ecosystem Analysis"],
  ["ENVS 1492", "SES-Aquatic Ecosystem Analysis"],
  ["ENVS 1493", "SES-Environmental Science Elective"],
  ["ENVS 1545", "The Theory and Practice of Sustainable Investing"],
  ["ENVS 1555", "Urban Agriculture: The Importance of Localized Food Systems"],
  ["ENVS 1557", "Birding Communities"],
  [
    "ENVS 1574",
    "Engaged Climate Policy in the U.S.: Rhode Island and Washington, DC",
  ],
  ["ENVS 1605", "Glaciers and Climate Change"],
  ["ENVS 1925", "Energy Policy and Politics"],
  ["ENVS 1970", "Independent Study"],
  ["ENVS 1971", "Independent Study"],
  ["ENVS 2450", "Exchange Scholar Program"],
  ["ENVS 2981", "Reading and Research"],
  ["ENVS 2990", "Thesis Preparation"],
  ["FREN 0100", "Basic French"],
  ["FREN 0200", "Basic French"],
  ["FREN 0300", "Intermediate French I"],
  ["FREN 0400", "Intermediate French II"],
  ["FREN 0500", "Writing and Speaking French I"],
  ["FREN 0600", "Writing and Speaking French II"],
  ["FREN 0620", "Writing and Speaking French II: Littérature:Nature/ Culture"],
  ["FREN 0720F", "The 19th-Century Novel and its Others"],
  [
    "FREN 1020A",
    "Histoire de la langue française: usages, politiques et enjeux du français",
  ],
  ["FREN 1040D", "Molière et son monde"],
  ["FREN 1110F", "Le Roman contemporain"],
  ["FREN 1130G", "Modernismes poétiques"],
  ["FREN 1330A", "Fairy Tales and Culture"],
  ["FREN 1410I", "Sorcellerie et Renaissance: le sort de la sorcière"],
  ["FREN 1970", "Individual Independent Study"],
  ["FREN 1990", "Senior Thesis"],
  ["FREN 2150E", "Théories et fictions des Lumières"],
  ["FREN 2170O", "Ivresses"],
  ["FREN 2450", "Exchange Scholar Program"],
  ["FREN 2610F", "French Ecological Thought"],
  ["FREN 2970", "Preliminary Examination Preparation"],
  ["FREN 2980", "Reading and Research"],
  ["FREN 2990", "Thesis Preparation"],
  ["GNSS 0710", "Feminist Digital Humanities"],
  ["GNSS 1510A", "Reproductive In/Justice"],
  [
    "GNSS 1711",
    "Speech and Silence, Trust, Rage and Fear: An Inquiry into the Possibility of Intimacy",
  ],
  ["GNSS 1810", "Independent Study and Research"],
  ["GNSS 1820", "Independent Study and Research"],
  ["GNSS 1961T", "Transpacific Femininities"],
  ["GNSS 1970", "Directed Research and Thesis"],
  ["GNSS 1980", "Directed Research and Thesis"],
  ["GNSS 1990", "Senior Seminar"],
  ["GNSS 2450", "Exchange Scholar Program"],
  [
    "GNSS XLIST",
    "Courses of Interest to Concentrators in Gender and Sexuality Studies",
  ],
  ["GRMN 0300", "Intermediate German I"],
  ["GRMN 0400", "Intermediate German II"],
  ["GRMN 0500F", "Twentieth-Century German Culture"],
  ["GRMN 1341D", "Philosophierende Hunde – Philosophizing Dogs"],
  ["GRMN 1341E", "Prague Circles"],
  ["GRMN 1441H", "Goethe Amongst Others"],
  ["GRMN 1970", "Independent Study"],
  ["GRMN 1990", "Senior Conference"],
  ["GRMN 2450", "Exchange Scholar Program"],
  ["GRMN 2970", "Preliminary Examination Preparation"],
  ["GRMN 2980", "Reading and Research"],
  ["GRMN 2990", "Thesis Preparation"],
  [
    "GRMN XLIST",
    "Courses of Interest to Students Concentrating in German Studies",
  ],
  [
    "GRMN 2662F",
    "Police, Strike, Justice: Revisiting Walter Benjamin’s “Critique of Violence”",
  ],
  ["HISP 0100", "Basic Spanish"],
  ["HISP 0200", "Basic Spanish"],
  ["HISP 0110", "Intensive Basic Spanish"],
  ["HISP 0300", "Intermediate Spanish I"],
  ["HISP 0400", "Intermediate Spanish II"],
  ["HISP 0490A", "Spanish for Health Care Workers"],
  ["HISP 0500", "Advanced Spanish I"],
  ["HISP 0600", "Advanced Spanish II"],
  ["HISP 0650", "Advanced Spanish Through Literature &amp; Film"],
  ["HISP 0710B", "Hispanic Culture Through Cinema"],
  ["HISP 0750E", "Topics in Hispanic Culture and Civilization"],
  ["HISP 0710C", "Introducción a la lingüística hispánica"],
  ["HISP 0710E", "Introduction to Professional Translation and Interpretation"],
  ["HISP 0740", "Intensive Survey of Spanish Literature"],
  ["HISP 0750B", "The Latin American Diaspora in the US"],
  [
    "HISP 0750Q",
    "Health, Illness and Medicine in Spanish and Spanish American Literature and Film",
  ],
  [
    "HISP 1290D",
    "Contra Franco vivíamos mejor? Literature and Culture of the Spanish Dictatorship (1939-1975)",
  ],
  ["HISP 1290P", "Federico García Lorca, 1898-1936"],
  ["HISP 1330D", "Patriots, Rogues, and Lovers"],
  [
    "HISP 1330W",
    "War, Revolution and the Cult of the Hero in Latin American Culture",
  ],
  ["HISP 1331K", "Borges y la Literatura Fantástica"],
  ["HISP 1980", "Independent Study"],
  ["HISP 1990", "Senior Thesis Preparation"],
  ["HISP 2350H", "The History of Wonder in Colonial Spanish America"],
  ["HISP 2350V", "The Politics of Romanticism in Spanish American Literature"],
  ["HISP 2450", "Exchange Scholar Program"],
  ["HISP 2620O", "Authorship and Authoritarianism in Spain and Latin America"],
  ["HISP 2970", "Preliminary Examination Preparation"],
  ["HISP 2990", "Thesis Preparation"],
  ["HISP 2991", "Thesis Preparation"],
  ["HISP XLIST", "Courses of Interest to Concentrators in Hispanic Studies"],
  ["HIST 0233", "Colonial Latin America"],
  [
    "HIST 0252",
    "The American Civil War in Global Perspective: History, Law, and Popular Culture",
  ],
  [
    "HIST 0270A",
    "From Fire Wielders to Empire Builders: Human Impact on the Global Environment before 1492",
  ],
  ["HIST 0523P", "The First World War"],
  ["HIST 0537B", "Tropical Delights: Imagining Brazil in History and Culture"],
  ["HIST 0556A", "Sport in American History"],
  ["HIST 0580M", "The Age of Revolutions, 1760-1824"],
  ["HIST 1030", "Entangled South Africa"],
  ["HIST 1123", "China's Socialist Dreams"],
  [
    "HIST 1202",
    "Formation of the Classical Heritage: Greeks, Romans, Jews, Christians, and Muslims",
  ],
  ["HIST 1205", "The Long Fall of the Roman Empire"],
  ["HIST 1262M", "Truth on Trial: Justice in Italy, 1400-1800"],
  ["HIST 1310", "History of Brazil"],
  ["HIST 1320", "Rebel Island: Cuba, 1492-Present"],
  ["HIST 1333", "The Mexican Revolution"],
  ["HIST 1620", "Resisting Empire: Gandhi and the Making of Modern South Asia"],
  [
    "HIST 1381",
    "Latin American History and Film: Memory, Narrative and Nation",
  ],
  ["HIST 1501", "The American Revolution"],
  [
    "HIST 1512",
    "First Nations: The People and Cultures of Native North America to 1800",
  ],
  ["HIST 1825J", "History of Artificial Intelligence"],
  [
    "HIST 1954F",
    "Globalism before Globalization: The Interconnected World of the Early Middle Ages",
  ],
  ["HIST 1965C", "Stalinism"],
  ["HIST 1968A", "Approaches to the Middle East"],
  ["HIST 1969A", "Israel-Palestine: Lands and Peoples I"],
  ["HIST 1969C", "Debates in Middle Eastern History"],
  ["HIST 1975J", "Portuguese Discoveries and Early Modern Global History"],
  ["HIST 1990", "Undergraduate Reading Courses"],
  ["HIST 2450", "Exchange Scholar Program"],
  ["HIST 2890", "Preliminary Examination Preparation"],
  ["HIST 2910", "Reading and Research"],
  ["HIST 2970S", "Intellectual History of Exile"],
  ["HIST 1974M", "Early Modern Globalization"],
  ["HIST 2981D", "Histories of Sexualities"],
  ["HIST 2981M", "Intimate Governance: Family, Household, and the State"],
  ["HIST 2981T", "Race and Species"],
  ["HIST 2990", "Thesis Preparation"],
  [
    "HIAA 0062",
    "Dutch and Flemish Art: Visual Culture of the Netherlands in the Seventeenth Century",
  ],
  ["HIAA 0850", "Modern Architecture"],
  ["HIAA 1620", "Arts Between Europe and the World: 1500-1700"],
  [
    "HIAA 1920",
    "Individual Study Project in the History of Art and Architecture",
  ],
  ["HIAA 1990", "Honors Thesis"],
  ["HIAA 2450", "Exchange Scholar Program"],
  ["HIAA 2880", "Race and Architecture"],
  ["HIAA 2940", "Master's Qualifying Paper Preparation"],
  ["HIAA 2980", "Individual Reading (Single Credit)"],
  ["HIAA 2981", "Individual Reading (Double Credit)"],
  ["HIAA 2982", "Individual Reading for the Doctoral Candidate"],
  ["HIAA 2983", "Dissertation Research"],
  ["HIAA 2990", "Thesis Preparation"],
  ["HIAA 2991", "Dissertation Preparation"],
  ["HIAA 2992", "Master's Thesis Preparation"],
  ["HIAA XLIST", "Courses of Interest to Concentrators"],
  ["IAPA 0200", "Foundations of Development"],
  ["IAPA 1203", "History of American Intervention"],
  ["IAPA 1205", "International Law"],
  ["IAPA 1401", "Economic Development in Latin America"],
  ["IAPA 1700", "Economics for Public Policy"],
  ["IAPA 1803", "Humanitarian Response in Modern Conflict"],
  ["IAPA 1803E", "Social Entrepreneurship"],
  ["IAPA 1804D", "Legal Methods for Public Policy"],
  [
    "IAPA 1804Q",
    "French Colonialism in Global Perspective, 19th-20th Centuries",
  ],
  ["IAPA 1809C", "Senior Thesis Preparation"],
  ["IAPA 1814A", "Roots of Crisis in Central America"],
  ["IAPA 1817A", "Senior Honors Thesis"],
  ["IAPA 1818A", "Individual Research Project"],
  ["IAPA 1852", "Individual Research Project"],
  ["ITAL 0100", "Elementary Italian"],
  ["ITAL 0110", "Intensive Elementary Italian"],
  ["ITAL 0300", "Intermediate Italian I"],
  ["ITAL 0400", "Intermediate Italian II"],
  ["ITAL 0500", "Advanced Italian I"],
  ["ITAL 1030B", "Modernity, Italian Style"],
  ["ITAL 1260", "Truth on Trial: Justice in Italy, 1400-1800"],
  ["ITAL 1610", "The Divina Commedia: Inferno and Purgatorio"],
  ["ITAL 1990", "Senior Conference"],
  ["ITAL 2100", "Introduction to Italian Studies"],
  ["ITAL 2220", "New Perspectives on Fascism"],
  ["ITAL 2450", "Exchange Scholar Program"],
  ["ITAL 2820", "Italian Studies Colloquium"],
  ["ITAL 2970", "Preliminary Examination Preparation"],
  ["ITAL 2980", "Reading and Research"],
  ["ITAL 2990", "Thesis Preparation"],
  ["HEBR 0100", "Elementary Hebrew"],
  ["HEBR 0200", "Elementary Hebrew"],
  ["HEBR 0300", "Intermediate Hebrew"],
  ["HEBR 0400", "Intermediate Hebrew"],
  ["HEBR 0500", "Writing and Speaking Hebrew"],
  [
    "HEBR 0600",
    "Issues in Contemporary Israeli Society, Politics, and Culture in Hebrew",
  ],
  ["JUDS 0050H", "Israel's Wars"],
  ["JUDS 0050K", "Hope, Despair, and Longing in Jewish Thought"],
  ["JUDS 0617", "Jewish Women: Between Conformity and Agency"],
  ["JUDS 0681", "Great Jewish Books"],
  ["JUDS 0830", "The Bible as Literature"],
  ["JUDS 0902", "History of the Holocaust"],
  ["JUDS 1614", "Heidegger, the Jews, and the Crisis of Liberalism"],
  [
    "JUDS 1690",
    "Prophets and Priests in Exile: Biblical Literature of the 6th Century BCE",
  ],
  ["JUDS 1713", "Introduction to Yiddish Culture and Language"],
  ["JUDS 1970", "Individual Study Projects"],
  ["JUDS 1975", "Honors Thesis Semester I"],
  ["JUDS 1976", "Honors Thesis Semester II"],
  ["JUDS 2450", "Exchange Scholar Program"],
  ["SIGN 0200", "American Sign Language I, II"],
  ["SIGN 0300", "American Sign Language III"],
  ["SIGN 0400", "American Sign Language IV"],
  ["SIGN 0500", "American Sign Language V"],
  ["ARAB 0100", "First-Year Arabic"],
  ["ARAB 0200", "First-Year Arabic"],
  ["ARAB 0300", "Second-Year Arabic"],
  ["ARAB 0400", "Second-Year Arabic"],
  ["ARAB 0500", "Third-Year Arabic"],
  ["ARAB 0600", "Third-Year Arabic"],
  ["ARAB 0700", "Advanced Arabic: Tales of the City"],
  ["ARAB 0850", "Advanced reading and composition in Arabic: Kalila wa- Dimna"],
  ["ARAB 1990", "Special Topics in Arabic Language, Literature, and Culture"],
  ["ARAB 2450", "Exchange Scholar Program"],
  ["EINT 2200", "Academic Interactions"],
  ["EINT 2300", "Negotiating an American Classroom"],
  ["EINT 2400", "Speaking Professionally for Internationals"],
  ["EINT 2500", "Advanced Articulation Tutorial"],
  ["HNDI 0100", "Beginning Hindi or Urdu"],
  ["HNDI 0200", "Beginning Hindi or Urdu"],
  ["HNDI 0300", "Intermediate Hindi-Urdu"],
  ["HNDI 0400", "Intermediate Hindi-Urdu"],
  ["HNDI 1080", "Advanced Hindi-Urdu"],
  ["LANG 1900", "Independent Study in Languages"],
  ["LANG 2450", "Exchange Scholar Program"],
  ["PRSN 0100", "Basic Persian"],
  ["PRSN 0200", "Basic Persian"],
  ["PRSN 0300", "Intermediate Persian Language and Culture"],
  ["PRSN 0400", "Intermediate Persian Language and Culture"],
  ["PRSN 2980", "Reading and Research"],
  ["TKSH 0100", "Introduction to Turkish Language and Culture I"],
  ["TKSH 0200", "Introduction to Turkish"],
  ["TKSH 0300", "Intermediate Turkish"],
  ["TKSH 0400", "Intermediate Turkish II"],
  ["TKSH 0720A", "Understanding Modern Turkey Through Film and Literature"],
  ["YORU 0100", "Introduction to Yoruba I"],
  ["YORU 0200", "Introduction to Yoruba II"],
  ["YORU 0300", "Intermediate Yoruba I"],
  ["YORU 0400", "Intermediate Yoruba II"],
  [
    "LACA 0500",
    "Around Latin America in 80 Days: An Historical and Cultural Journey",
  ],
  [
    "LACA 1900",
    "Preparation for Honors and Capstone Projects on Latin American and Caribbean Topics",
  ],
  ["LACA 1990", "Individual Thesis Preparation"],
  ["LACA 1991", "Individual Thesis Preparation"],
  ["LACA 1994", "Independent Readings in Latin American and Caribbean Studies"],
  ["LACA 1995", "Independent Readings in Latin American and Caribbean Studies"],
  ["LACA 2980", "Graduate level independent study"],
  ["LITR 0100A", "Introduction to Fiction"],
  ["LITR 0100B", "Introduction to Poetry"],
  ["LITR 0110A", "Fiction I"],
  ["LITR 0110B", "Poetry I"],
  ["LITR 0110H", "Digital &amp; Cross-Disciplinary Language Arts 1"],
  ["LITR 0210A", "Fiction Writing II"],
  ["LITR 0210B", "Poetry Writing II"],
  ["LITR 0710", "Writers on Writing Seminar"],
  ["LITR 1010A", "Advanced Fiction"],
  ["LITR 1010B", "Advanced Poetry"],
  ["LITR 1010E", "Advanced Screenwriting"],
  ["LITR 1110N", "Workshop for Potential Literature"],
  ["LITR 1110S", "Fiction into Film"],
  ["LITR 1151Q", "Great Adventure"],
  ["LITR 1152Q", "Land Arts"],
  ["LITR 1200", "Writers on Writing"],
  [
    "LITR 1300",
    "Independent Study in Reading, Research, and Writing About Literature",
  ],
  ["LITR 1310", "Independent Study in Creative Writing"],
  ["LITR 2010A", "Graduate Fiction"],
  ["LITR 2010B", "Graduate Poetry"],
  [
    "LITR 2230",
    "Graduate Independent Study in Reading, Research, and Writing About Literature",
  ],
  ["LITR 2310", "Graduate Independent Studies in Literary Writing"],
  ["LITR 2450", "Exchange Scholar Program"],
  ["MATH 0060", "Analytic Geometry and Calculus"],
  ["MATH 0070", "Calculus with Applications to Social Science"],
  ["MATH 0090", "Introductory Calculus, Part I"],
  ["MATH 0100", "Introductory Calculus, Part II"],
  ["MATH 0520", "Linear Algebra"],
  ["MATH 0180", "Intermediate Calculus"],
  ["MATH 0200", "Intermediate Calculus (Physics/Engineering)"],
  ["MATH 0350", "Honors Calculus"],
  ["MATH 0420", "Introduction to Number Theory"],
  ["MATH 0540", "Honors Linear Algebra"],
  ["MATH 1010", "Analysis: Functions of One Variable"],
  ["MATH 1040", "Fundamental Problems of Geometry"],
  ["MATH 1060", "Differential Geometry"],
  ["MATH 1110", "Ordinary Differential Equations"],
  ["MATH 1120", "Partial Differential Equations"],
  ["MATH 1130", "Functions of Several Variables"],
  ["MATH 1140", "Functions Of Several Variables"],
  ["MATH 1230", "Graph Theory"],
  ["MATH 1260", "Complex Analysis"],
  ["MATH 1270", "Topics in Functional Analysis"],
  ["MATH 1410", "Topology"],
  ["MATH 1530", "Abstract Algebra"],
  ["MATH 1540", "Topics in Abstract Algebra"],
  ["MATH 1560", "Number Theory"],
  ["MATH 1580", "Cryptography"],
  ["MATH 1610", "Probability"],
  ["MATH 1620", "Mathematical Statistics"],
  ["MATH 1810B", "A Second Course in Linear Algebra"],
  ["MATH 1970", "Honors Conference"],
  ["MATH 2010", "Differential Geometry"],
  ["MATH 2050", "Algebraic Geometry"],
  ["MATH 2060", "Algebraic Geometry"],
  ["MATH 2110", "Introduction to Manifolds"],
  ["MATH 2210", "Real Function Theory"],
  ["MATH 2220", "Real Function Theory"],
  ["MATH 2250", "Complex Function Theory"],
  ["MATH 2260", "Complex Function Theory"],
  ["MATH 2410", "Topology"],
  ["MATH 2420", "Algebraic Topology"],
  ["MATH 2450", "Exchange Scholar Program"],
  ["MDVL 0510K", "The 1001 Nights (COLT 0510K)"],
  ["MDVL 0610", "Sufi Islam (RELS 0610)"],
  ["MDVL 1120D", "Alcuin (LATN 1120D)"],
  ["MDVL 1120G", "The Idea of Self (CLAS 1120G)"],
  [
    "MDVL 1430B",
    "Art and Exemplarity in Medieval and Early Modern Literature (COLT 1430B)",
  ],
  ["MATH 2520", "Algebra"],
  ["MATH 2530", "Number Theory"],
  ["MATH 2540", "Number Theory"],
  ["MATH 2980", "Reading and Research"],
  ["MATH 2990", "Thesis Preparation"],
  ["MATH XLIST", "Courses of Interest to Students Majoring in Mathematics"],
  ["MDVL 1610", "The Divina Commedia: Inferno and Purgatorio (ITAL 1610)"],
  [
    "MDVL 1900Y",
    "Medieval Manuscript Studies: Paleography, Codicology, and Interpretation (ENGL 1900Y)",
  ],
  [
    "MDVL 1954F",
    "Globalism before Globalization: The Interconnected World of the Early Middle Ages (HIST 1954F)",
  ],
  ["MDVL 1970", "Independent Study"],
  ["MDVL 1990", "Honors Thesis"],
  [
    "MDVL 2030D",
    "Fifteenth-Century Sentimental Romances and Celestina (HISP 2030D)",
  ],
  ["MES 1970", "Individual Research Project"],
  ["MES 1971", "Senior Honors Thesis"],
  [
    "MES 2000A",
    "Decolonizing the Racialized Female Subject: Black and Indigenous Women’s Self-Making Under Empire",
  ],
  [
    "MES XLIST",
    "Courses of Interest to Students Concentrating in Middle East Studies",
  ],
  ["MCM 1204J", "A New Black Gaze"],
  ["MCM 1506U", "Is that a Fact?"],
  [
    "MCM 1980",
    "Honors Thesis/Project Research in Modern Culture and Media (Part 1)",
  ],
  ["MCM 1990", "Honors Thesis/Project in Modern Culture and Media (Part 2)"],
  ["MCM 2110Y", "The Literary Fact and the Work of Critique"],
  ["MCM 2120O", "Concepts of Technology and Media"],
  ["MCM 2450", "Exchange Scholar Program"],
  ["MCM 2990", "Thesis Preparation"],
  ["MUSC 0021F", "Popular Music and Society in Latin America"],
  ["MUSC 0021J", "Stephen Sondheim and the American Musical"],
  ["MUSC 0068", "Music in China Since 1900"],
  ["MUSC 0400A", "Introduction to Music Theory"],
  ["MUSC 0550", "Theory of Tonal Music I"],
  ["MUSC 0560", "Theory of Tonal Music II"],
  ["MUSC 0600", "Chorus"],
  ["MUSC 0610", "Orchestra"],
  ["MUSC 0630", "Jazz Band"],
  ["MUSC 0640", "Ghanaian Drumming and Dancing Ensemble"],
  ["MUSC 0642", "World Music Ensemble"],
  [
    "MUSC 0810",
    "Applied Music Program: Instruction in Vocal or Instrumental Music",
  ],
  ["MUSC 0910", "Medieval and Renaissance Music"],
  ["MUSC 1100", "Introduction to Composition"],
  ["MUSC 1110", "Seminar in Composition"],
  ["MUSC 1120", "The Technique of Orchestration"],
  [
    "MUSC 1200",
    "Seminar in Electronic Music: Recording Studio as Compositional Tool",
  ],
  ["MUSC 1240R", "Rap as Storytelling"],
  ["MUSC 1255", "Sound Design - Synthesis and Spatialization"],
  ["MUSC 1680", "Musical Performance: Theatricality, Body, and Spectacle"],
  ["MUSC 1700", "Score Reading and Conducting"],
  [
    "MUSC 1810",
    "Applied Music Program: Instruction in Vocal or Instrumental Music",
  ],
  ["MUSC 1905A", "Music and Cultural Policy"],
  ["MUSC 1970", "Individual Independent Study"],
  ["MUSC 1980", "Group Independent Study"],
  [
    "MUSC 2080E",
    "Seminar in Ethnomusicology: Historiography of Music and the Performing Arts",
  ],
  ["MUSC 2130", "Asian Musical Modernisms"],
  ["MUSC 2210", "Digital Performance"],
  ["MUSC 2450", "Exchange Scholar Program"],
  ["MUSC 2970", "Preliminary Examination Preparation"],
  ["MUSC 2980", "Reading and Research"],
  ["MUSC 2990", "Thesis Preparation"],
  ["PHIL 1990", "Independent Studies"],
  ["PHIL 1995", "Senior Thesis"],
  ["PHIL 2450", "Exchange Scholar Program"],
  ["PHIL 2970", "Preliminary Examination Preparation"],
  ["PHIL 2980", "Research in Philosophy"],
  ["PHIL 2990", "Thesis Preparation"],
  ["PHIL XLIST", "Courses of Interest to Philosophy Concentrators"],
  ["PHYS 0040", "Basic Physics B"],
  ["PHYS 0050", "Foundations of Mechanics"],
  ["PHYS 0070", "Analytical Mechanics"],
  [
    "PHYS 0100",
    "Flat Earth to Quantum Uncertainty: On the Nature and Meaning of Scientific Explanation",
  ],
  ["PHYS 0112", "Extra-Solar Planets and the Search for Extraterrestrial Life"],
  ["PHYS 0150", "The Jazz of Modern Physics"],
  ["PHYS 0220", "Astronomy"],
  ["PHYS 0270", "Astronomy and Astrophysics"],
  ["PHYS 0470", "Electricity and Magnetism"],
  ["PHYS 0500", "Advanced Classical Mechanics"],
  ["PHYS 0560", "Experiments in Modern Physics"],
  ["PHYS 0720", "Methods of Mathematical Physics"],
  ["PHYS 0790", "Physics of Matter"],
  ["PHYS 1100", "General Relativity"],
  ["PHYS 1170", "Introduction to Nuclear and High Energy Physics"],
  ["PHYS 1250", "Stellar Structure and the Interstellar Medium"],
  ["PHYS 1410", "Quantum Mechanics A"],
  ["PHYS 1420", "Quantum Mechanics B"],
  ["PHYS 1510", "Advanced Electromagnetic Theory"],
  ["PHYS 1530", "Thermodynamics and Statistical Mechanics"],
  ["PHYS 1560", "Modern Physics Laboratory"],
  ["PHYS 1610", "Biological Physics"],
  ["PHYS 1720", "Methods of Mathematical Physics"],
  ["PHYS 1970J", "Introduction to Fluids"],
  ["PHYS 1980", "Undergraduate Research in Physics"],
  ["PHYS 1990", "Senior Conference Course"],
  ["PHYS 2320", "Quantum Theory of Fields II"],
  ["PHYS 2420", "Solid State Physics II"],
  ["PHYS 2450", "Exchange Scholar Program"],
  ["PHYS 2630", "Biological Physics"],
  ["PHYS 2711", "Seminar in Research Topics"],
  ["PHYS 2970", "Preliminary Examination Preparation"],
  ["PHYS 2980", "Research in Physics"],
  ["PHYS 2981", "Research in Physics"],
  ["PHYS 2990", "Thesis Preparation"],
  ["POLS 0010", "Introduction to the American Political Process"],
  ["POLS 0110", "Introduction to Political Thought"],
  ["POLS 0400", "Introduction to International Politics"],
  ["POLS 0500", "Foundations of Political Analysis"],
  ["PHYS 2710", "Seminar in Research Topics"],
  ["POLS 0820I", "Crime, Mafias and Prison"],
  ["POLS 0920A", "Bleeding Heart Libertarianism"],
  ["POLS 1020", "Politics of the Illicit Global Economy"],
  ["POLS 1040", "Ancient Political Thought"],
  ["POLS 1085", "Injustice"],
  ["POLS 1100", "U.S"],
  ["POLS 1130", "The American Presidency"],
  ["POLS 1150", "Prosperity: The Ethics and Economics of Wealth Creation"],
  ["POLS 1210", "Latin American Politics"],
  ["POLS 1225", "The Politics of Nuclear Weapons"],
  ["POLS 1265", "Political Institutions of East Asian Democracies"],
  ["POLS 1280", "Politics, Economy and Society in India"],
  ["POLS 1310", "African American Politics"],
  ["POLS 1360", "U.S"],
  ["POLS 1400", "North Atlantic Politics after the Cold War"],
  ["POLS 1455", "Crime, Punishment, and Politics"],
  ["POLS 1520", "Introduction to Feminist Theory"],
  ["POLS 1560", "American Foreign Policy"],
  ["POLS 1600", "Political Research Methods"],
  ["POLS 1730", "Politics of Globalization"],
  ["POLS 1770", "Education, Inequality, and American Democracy"],
  ["POLS 1820F", "Black Protest: Theory and Praxis"],
  ["POLS 1820R", "Extralegal Governance and the Problem of Social Order"],
  ["POLS 1820X", "Democratic Erosion"],
  ["POLS 1821I", "Issues in Democratic Theory"],
  ["POLS 1822A", "Nuclear Weapons and International Politics"],
  ["POLS 1822F", "Social Movements and Struggles for Justice"],
  ["POLS 1822J", "Ethics of War and Peace"],
  ["POLS 1822W", "Congressional Investigations"],
  ["POLS 1823C", "Ancient Political Thought"],
  ["POLS 1823J", "Freedom, Work, Leisure"],
  ["POLS 1823W", "American Political Thought"],
  ["POLS 1825I", "The Politics of the Harlem Renaissance"],
  ["POLS 1823Z", "Gender and Public Policy"],
  ["POLS 1824C", "Political Communication"],
  ["POLS 1824T", "US-China Relations"],
  ["POLS 1825G", "Race, The Classics and Democratic Theory"],
  ["POLS 1826I", "Politics of Poverty in America"],
  ["POLS 1826J", "The History of Liberalism"],
  ["POLS 1910", "Senior Honors Thesis Preparation"],
  ["POLS 1920", "Senior Honors Thesis Preparation"],
  ["POLS 1970", "Individual Reading and Research"],
  ["POLS 1971", "Individual Reading and Research"],
  ["POLS 2050", "Preparing the Prospectus I"],
  ["POLS 2051", "Preparing the Prospectus II"],
  [
    "POLS 2090D",
    "Models of Excellence in Comparative Research: Classic Works and the Scholars Who Produced Them",
  ],
  ["POLS 2090G", "Readings in American Institutions"],
  ["POLS 2100", "Proseminar in American Politics"],
  ["POLS 2111", "Comparative Politics Grad Research Workshop"],
  ["POLS 2130", "Proseminar in International Relations"],
  ["POLS 2140", "Contemporary Security Issues"],
  [
    "POLS 2180",
    "Business-State Relations in the Advanced Industrial Countries",
  ],
  ["POLS 2300", "Latin American Political Thought"],
  [
    "POLS 2355",
    "Tragedies of Remarriage: Stanley Cavell’s Film Philosophy in Focus",
  ],
  ["POLS 2360", "Proseminar in Political Theory II"],
  ["POLS 2450", "Exchange Scholar Program"],
  ["POLS 2975", "Research Design"],
  ["POLS 2976", "Field Survey and Research Design"],
  ["POLS 2980", "Individual Reading and Research"],
  ["POLS 2981", "Individual Reading and Research"],
  ["POLS 2990", "Thesis Preparation"],
  ["POLS 2991", "Thesis Research and Preparation"],
  ["POBS 0105", "Accelerated Portuguese"],
  ["POBS 0400", "Writing and Speaking Portuguese"],
  ["POBS 0910", "On the Dawn of Modernity"],
  ["POBS 1600D", "Portuguese Discoveries and Early Modern Globalization"],
  [
    "POBS 1740",
    "Artful Teaching: Intersecting the Arts with Foreign and Second Language Acquisition",
  ],
  [
    "POBS 1800C",
    "Constructing Men, Projecting Masculinity: Questioning Gender, Sex, and Sexuality in Brazil",
  ],
  ["POBS 1970", "Reading and Guided Study"],
  ["POBS 1990", "Research and Preparation of Honors Projects"],
  ["POBS 2450", "Exchange Scholar Program"],
  ["POBS 2600P", "Fernando Pessoa and Co"],
  ["POBS 2970", "Preliminary Examination Preparation"],
  ["POBS 2980", "Reading and Guided Study"],
  ["POBS 2990", "Thesis Preparation"],
  ["MPA 2445", "Policy Analysis and Problem Solving"],
  ["MPA 2981", "Independent Graduate Study"],
  ["PHP 0310", "Health Care in the United States"],
  ["PHP 0850", "Fundamentals of Epidemiology"],
  ["PHP 1100", "Comparative Health Care Systems"],
  ["PHP 1501", "Essentials of Data Analysis"],
  ["PHP 1510", "Principles of Biostatistics and Data Analysis"],
  ["PHP 1540", "Alcohol Use and Misuse"],
  ["PHP 1560", "Statistical Programming in R"],
  ["PHP 1690", "Technology and Health Behavior Change"],
  ["PHP 1700", "Current Topics in Environmental Health"],
  ["PHP 1890", "The Craving Mind"],
  [
    "PHP 1900",
    "Epidemiology of Disorders and Diseases of Childhood and Young Adulthood",
  ],
  ["PHP 1910", "Public Health Senior Seminar"],
  ["PHP 1920", "Social Determinants of Health"],
  ["PHP 1964", "Cancer Epidemiology and Prevention"],
  ["PHP 1970", "Independent Study"],
  ["PHP 1980", "Honors Thesis Preparation"],
  ["PHP 2023", "Maternal and Child Health in the United States"],
  ["PHP 2030", "Clinical Trials Methodology"],
  ["PHP 2060", "Qualitative Methods in Health Research"],
  ["PHP 2072", "Applied Public Health: Policy, leadership and communication"],
  ["PHP 2090", "Research Grant Writing for Public Health"],
  ["PHP 2150", "Foundations in Epidemiologic Research Methods"],
  ["PHP 2250", "Advanced Quantitative Methods in Epidemiologic Research"],
  ["PHP 2300", "Research Methods in Behavioral Science"],
  [
    "PHP 2325",
    "Place Matters: Exploring Community-Level Contexts on Health Behaviors, Outcomes and Disparities",
  ],
  ["PHP 2340", "Behavioral and Social Science Theory for Health Promotion"],
  ["PHP 2370", "Etiology of Substance Use Disorders"],
  ["PHP 2410E", "Medicare: A Data Based Policy Examination"],
  ["PHP 2510", "Principles of Biostatistics and Data Analysis"],
  ["PHP 2550", "Practical Data Analysis"],
  ["PHP 2560", "Statistical Programming with R"],
  ["PHP 2445", "Minding the Gap: The U.S"],
  ["PHP 2451", "Exchange Scholar Program"],
  ["PHP 2601", "Linear Models"],
  [
    "PHP 2720",
    "Implementing Public Health Programs and Interventions in the Global South",
  ],
  ["PHP 2950", "Doctoral Seminar in Public Health"],
  ["PHP 2981", "Graduate Independent Study and Thesis Research (half- credit)"],
  ["PHP 2985", "MPH Independent Study for Thesis Preparation and Research"],
  ["PHP 2988", "SPH Doctoral Teaching Experience (TE)"],
  ["PHP 2990", "Thesis Preparation"],
  ["PHP XLIST", "Courses of Interest to Concentrators in Community Health"],
  ["COST 0036", "Love and War in India"],
  ["COST 0125", "Your Moment of Zen"],
  [
    "COST 0520",
    "Tai Chi, Qigong, and Traditions of Energy Cultivation in China",
  ],
  ["COST 0560", "Contemplation and Social Action"],
  [
    "COST 1082",
    "Me, Myself, and I: Exploring Senses of Self from a Multidisciplinary Perspective",
  ],
  ["COST 1910", "Individual Study Project – Semester 1"],
  ["COST 1920", "Individual Study Project - Semester 2"],
  ["COST 1980", "Thesis Preparation"],
  ["RELS 0015", "Sacred Stories"],
  ["RELS 0036", "Love and War in India"],
  ["RELS 0045", "Buddhism and Death"],
  ["RELS 0080", "Japan: Nature, Ritual and the Arts"],
  ["RELS 0090K", "Christmas in America"],
  ["RELS 0095B", "Islam in Fiction: History, Romance, Satire"],
  ["RELS 0125", "Your Moment of Zen"],
  ["RELS 0290D", "Islamic Sexualities"],
  [
    "RELS 0520",
    "Tai Chi, Qigong, and Traditions of Energy Cultivation in China",
  ],
  ["RELS 0560", "Contemplation and Social Action"],
  ["RELS 0610", "Sufi Islam"],
  ["RELS 0750", "Law and Religion"],
  ["RELS 1000", "Methods in Religious Studies"],
  ["RELS 1325C", "The Virgin Mary in Christian Tradition"],
  ["RELS 1995", "Senior Capstone Seminar"],
  ["RELS 1999", "Thesis Preparation"],
  ["RELS 2000", "Theory of Religion"],
  ["RELS 2100F", "Seminar in Biblical Studies: Ugaritic"],
  ["RELS 2450", "Exchange Scholar Program"],
  ["RELS 2460", "Professionalization Seminar"],
  ["RELS 2890", "Preliminary Examination Preparation"],
  ["RELS 1742A", "Great Authors and Works of Italian Renaissance (ITAL 1320)"],
  ["RELS 1990", "Individual Study Project"],
  ["RELS 2910", "Independent Research"],
  ["RELS 2990", "Thesis Preparation"],
  ["EMOW 0081", "Architecture of the House Through Space and Time (HIAA 0081)"],
  ["EMOW 1320", "Great Authors and Works of Italian Renaissance (ITAL 1320)"],
  ["EMOW 1361L", "Milton (ENGL 1361L)"],
  [
    "EMOW 1410I",
    "Sorcellerie et Renaissance: le sort de la sorcière (FREN 1410I)",
  ],
  [
    "EMOW 1430B",
    "Art and Exemplarity in Medieval and Early Modern Literature (COLT 1430B)",
  ],
  [
    "EMOW 1825H",
    "Science, Medicine and Technology in the 17th Century (HIST 1825H)",
  ],
  ["EMOW 1980", "Independent Study in EMOW"],
  [
    "EMOW 2561V",
    "The Pursuit of Happiness: Transatlantic Literary Culture in the Long Eighteenth Century (ENGL 2561V)",
  ],
  ["SAST 1970", "Independent Study"],
  ["SAST XLIST", "Courses of Interest to Concentrators"],
  ["STS 1970", "Independent Study in Science and Society"],
  ["STS 1971", "Independent Study in Science and Society"],
  ["CZCH 0100", "Introductory Czech"],
  ["CZCH 0200", "Introductory Czech"],
  [
    "CZCH 1000",
    "Dimensions of Czech Animation: Contexts, Interpretations, and Dialogs with the East",
  ],
  ["RUSS 0100", "Introductory Russian"],
  ["RUSS 0110", "Intensive Russian"],
  ["RUSS 0200", "Introductory Russian"],
  ["RUSS 0300", "Intermediate Russian"],
  [
    "RUSS 0320A",
    "Dostoevsky's 'The Brothers Karamazov' - The Art of the Novel",
  ],
  ["RUSS 0400", "Intermediate Russian"],
  ["RUSS 0500", "Advanced Russian"],
  ["RUSS 0600", "Advanced Russian"],
  [
    "RUSS 1110",
    "Special Topics in Russian Studies I: Advanced Reading and Conversation",
  ],
  [
    "RUSS 1120",
    "Special Topics in Russian Studies II: Advanced Reading and Conversation",
  ],
  [
    "RUSS 1300",
    "Russian Literature in Translation II: Tolstoy to Solzhenitsyn",
  ],
  ["RUSS 1340", "The Russian Novel"],
  ["RUSS 2980", "Advanced Reading and Research"],
  ["RUSS 2990", "Thesis Preparation"],
  [
    "RUSS 1440",
    "Imagining Moscow: Utopia and Urban Spaces in 20th- Century Russian Culture",
  ],
  [
    "RUSS 1550",
    "Beyond the Kremlin: Russian Culture and Politics in the Twenty-First Century",
  ],
  ["RUSS 1848", "Central Europe: An Idea and its Literature"],
  ["RUSS 1870", "Gogol"],
  ["RUSS 1960", "Independent Study"],
  ["RUSS 2970", "Preliminary Examination Preparation"],
  [
    "SLAV 1300",
    "Sociolinguistics (with Case Studies on the Former USSR and Eastern Europe)",
  ],
  ["SLAV 1950", "Independent Study"],
  ["SLAV 1990", "Senior Thesis"],
  ["SLAV 2450", "Exchange Scholar Program"],
  ["SLAV 2980", "Advanced Reading and Research"],
  ["SLAV 2990", "Thesis Preparation"],
  ["SLAV XLIST", "Courses of Interest to Concentrators in Slavic Languages"],
  [
    "SOC 0020",
    "Perspectives on Social Interaction: An Introduction to Social Psychology",
  ],
  ["SOC 0030", "Race, Immigration, and the Making of Inequality"],
  ["SOC 0300", "Organizations and Society"],
  ["SOC 0300F", "Unequal From Birth: Child Health From a Social Perspective"],
  ["SOC 0300K", "Inequalities and Health"],
  ["SOC 0310", "Theory and Practice of Engaged Scholarship"],
  ["SOC 1010", "Classical Sociological Theory"],
  ["SOC 1020", "Methods of Social Research"],
  ["SOC 1100", "Introductory Statistics for Social Research"],
  ["SOC 1118", "Context Research for Innovation"],
  ["SOC 1128", "Migrants, Refugees and the Mediterranean"],
  ["SOC 1270", "Race, Class, and Ethnicity in the Modern World"],
  ["SOC 1281", "Migration in the Americas"],
  ["SOC 1315", "Macro-Organizational Theory: Organizations in Social Context"],
  ["SOC 1330", "Remaking the City"],
  ["SOC 1340", "Principles and Methods of Geographic Information Systems"],
  ["SOC 1430", "Social Structure and Personal Development"],
  ["SOC 1550", "Sociology of Medicine"],
  ["SOC 1871O", "Law, Innovation and Entrepreneurship"],
  ["SOC 1871Z", "Martial Arts, Culture, and Society"],
  [
    "SOC 1872G",
    "First-Generation College Students: A Sociological Perspective: A Sophomore Seminar",
  ],
  ["SOC 1873G", "The Geography of Urban Inequality"],
  ["SOC 1873H", "A Hip Hop Companion to Race and Ethnicity"],
  ["SOC 1873I", "Immigration and Inequality in the United States"],
  ["SOC 1950", "Senior Seminar"],
  ["SOC 1970", "Individual Research Project"],
  ["SOC 1980", "Senior Honors Thesis"],
  ["SOC 1990", "Senior Honors Thesis"],
  ["SOC 2010", "Multivariate Statistical Methods I"],
  ["SOC 2020", "Multivariate Statistical Methods II"],
  ["SOC 2040", "Classical Sociological Theory"],
  ["SOC 2050", "Contemporary Sociology"],
  ["SOC 2080", "Principles of Population"],
  ["SOC 2090", "Culture and Social Structure"],
  ["SOC 2210", "Qualitative Methods"],
  ["SOC 2230", "Techniques of Demographic Analysis"],
  ["SOC 2240", "Event History Analysis"],
  ["SOC 2260B", "Sociology of Discrimination"],
  ["SOC 2320", "Migration"],
  ["SOC 2430", "Fields and Methods of Social Research"],
  ["SOC 2450", "Exchange Scholar Program"],
  ["SOC 2460", "Sociology Paper Writing Seminar"],
  ["SOC 2500", "Teaching Practicum in Sociology"],
  ["SOC 2510", "Teaching Practicum in Sociology"],
  [
    "SOC 2612",
    "Geographic Information Systems and Spatial Analysis for the Social Sciences",
  ],
  ["SOC 2960C", "Urban Sociology"],
  ["SOC 2960F", "Global and Transnational Sociology"],
  ["SOC 2960T", "Economic Sociology"],
  ["SOC 2961M", "Computational Methods for Social Scientists"],
  ["SOC 2961P", "Power, Organizations, and Culture"],
  ["SOC 2970", "Preliminary Examination Preparation"],
  ["SOC 2980", "Reading and Research"],
  ["SOC 2981", "Reading and Research"],
  ["SOC 2990", "Dissertation Preparation"],
  ["SOC XLIST", "Courses of Interest to Students Concentrating in Sociology"],
  ["TAPS 0100", "Playwriting I"],
  ["TAPS 0200", "Playwriting II"],
  ["TAPS 0220", "Persuasive Communication"],
  ["TAPS 0230", "Acting"],
  ["TAPS 0250", "Introduction to Technical Theatre and Production"],
  ["TAPS 0260", "Stage Lighting"],
  ["TAPS 0310", "Beginning Modern Dance"],
  ["TAPS 0320", "Dance Composition"],
  [
    "TAPS 0360",
    "Viewpoints Technique: The Moving Body in Relation to Time, Space, and Ensemble",
  ],
  ["TAPS 0700", "Introduction to Theatre, Dance and Performance"],
  ["TAPS 0930A", "The Actor's Instrument: Voice and Speech"],
  ["TAPS 1100", "Stage Management"],
  [
    "TAPS 1230",
    "Global Theatre and Performance: Paleolithic to the Threshold of Modernity",
  ],
  ["TAPS 1250", "Late Modern and Contemporary Theatre and Performance"],
  ["TAPS 1280F", "Introduction to Set Design"],
  ["TAPS 1280K", "Mindfulness and Movement: Interoceptive Expressive Arts"],
  [
    "TAPS 1280M",
    "A Producer Prepares: Curation, Ethics, and the Entrepreneurial Practice of Arts Programming",
  ],
  ["TAPS 1280U", "Voice Over for the Actor"],
  ["TAPS 1280Y", "Issues in Performance Studies"],
  ["TAPS 1281E", "Directing Theory and Practice"],
  ["TAPS 1281Q", "Introduction to Critical Dance Studies"],
  ["TAPS 1281W", "Arts and Health: Theory"],
  ["TAPS 1281Z", "Arts and Health: Practice"],
  ["TAPS 1285", "Film Acting"],
  ["TAPS 1330", "Dance History: The 20th Century"],
  ["TAPS 1341", "Introduction to Ballet"],
  ["TAPS 1343", "Intermediate Ballet"],
  ["TAPS 1350", "Dance Performance and Repertory"],
  ["TAPS 1360", "Dance Performance and Repertory"],
  ["TAPS 1370", "New Works/World Traditions"],
  ["TAPS 1380", "Mise en Scene"],
  ["TAPS 1390", "Contemporary Mande Performance"],
  ["TAPS 1500H", "Advanced Playwriting"],
  ["TAPS 1970", "Independent Reading and Research"],
  ["TAPS 1990", "Senior Honors Thesis Preparation"],
  ["TAPS 2310", "Graduate Playwriting"],
  ["TAPS 2450", "Exchange Scholar Program"],
  ["TAPS 1670", "Latino/a Theatre and Performance"],
  ["TAPS 1750", "Choreorobotics 0101: Robotics and Choreography"],
  [
    "TAPS 2535",
    "Directing 1: Fundamentals in Analysis and Action for Brown/Trinity MFA Actors and Directors",
  ],
  ["TAPS 2545", "Dramaturgy"],
  ["TAPS 2565", "Acting Technique II: Strength, Expansion and Articulation"],
  ["TAPS 2585", "Directing II: Collaborative Communication"],
  ["TAPS 2605", "Fundamentals of Acting: Shakespeare and Classical Verse"],
  ["TAPS 2615", "Acting Technique III: Poetic Expression"],
  ["TAPS 2625", "Playwriting Dramaturgy Practicum"],
  ["TAPS 2635", "Directing III: The Director's Vision"],
  ["TAPS 2645", "Fall Directing Practicum"],
  ["TAPS 2655", "Advanced Acting: Shakespeare and Classical Verse"],
  ["TAPS 2665", "Acting Technique IV: Creativity and Virtuosity"],
  ["TAPS 2675", "Advanced Playwriting"],
  ["TAPS 2685", "Directing IV: Special Topics"],
  ["TAPS 2695", "Spring Directing Practicum"],
  ["TAPS 2705", "Third Year Practicum: The Actor as Creator"],
  ["TAPS 2970", "Comprehensive Examination Preparation"],
  ["TAPS 2975", "Thesis Workshop"],
  ["TAPS 2980", "Graduate Level Independent Reading and Research"],
  ["TAPS 2981", "Master's Thesis Research"],
  ["TAPS 2990", "Thesis Preparation"],
  ["UNIV 1520", "The Shaping of World Views"],
  ["URBN 0210", "The City: An Introduction to Urban Studies"],
  ["URBN 1870D", "Downtown Development"],
  ["URBN 1870M", "Urban Regimes in the American Republic"],
  ["URBN 1870T", "Transportation: An Urban Planning Perspective"],
  ["URBN 1871B", "Berlin: Global Metropolis (1945-2020)"],
  ["URBN 1943", "The Real Estate Development Process: An Entrepreneurial Lens"],
  ["VISA 0130", "Sculpture Foundation"],
  ["URBN 1970", "Independent Reading and Research"],
  ["URBN 1971", "Senior Honors Thesis I in Urban Studies"],
  ["URBN 1972", "Senior Honors Thesis II in Urban Studies"],
  ["URBN XLIST", "Courses of Interest to Concentrators in Urban Studies"],
  ["VISA 0120", "Foundation Media"],
  ["VISA 0140", "Photography Foundation"],
  ["VISA 0150", "Digital 2D Foundation"],
  ["VISA 0160", "Foundation Painting"],
  ["VISA 1110", "Drawing"],
  ["VISA 1210G", "Silkscreen"],
  ["VISA 1240", "Art of the Book"],
  ["VISA 2450", "Exchange Scholar Program"],
  ["VISA 1410", "Sculpture: Material Investigations"],
  ["VISA 1510", "Black and White Photography"],
  ["VISA 1520", "Digital Photography"],
  ["VISA 1800C", "Honors Seminar"],
  ["VISA 1910", "Individual Study Project in the Practice of Art"],
  ["VISA 1990", "Honors"],
];

export {
  majors,
  pronouns,
  greekLife,
  instruments,
  pickUpSports,
  varsitySports,
  CandAinterests,
  PAandWinterests,
  GHinterests,
  courseList,
  countries,
  states,
};
