const emptyProfile = {
  firstName: "",
  lastName: "",
  email: "",
  class: "",
  majorOne: "",
  majorTwo: "",
  majorThree: "",
  preferredPronouns: "",
  interestOne: "",
  interestTwo: "",
  interestThree: "",
  interestFour: "",
  interestFive: "",
  interests1: [],
  interests2: [],
  interests3: [],
  groupOne: "",
  groupTwo: "",
  groupThree: "",
  varsitySportOne: "",
  varsitySportTwo: "",
  affinitySportOne: "",
  affinitySportTwo: "",
  affinitySportThree: "",
  greekLife: "",
  favorites: {
    movie: "",
    book: "",
    tvShow: "",
    artist: "",
  },
  bio: "",
  courseOne: {},
  courseTwo: {},
  courseThree: {},
  courseFour: {},
  courseFive: {},
  loading: false,
  errors: {},
  validProfile: true,
  secondMajor: false,
  thirdMajor: false,
  secondVarsitySport: false,
  fifthCourse: false,
  careerOpen: false,
  artsOpen: false,
  fitnessOpen: false,
  hobbiesOpen: false,
  politicsOpen: false,
  sportsOpen: false,
  scienceOpen: false,
};

export default emptyProfile;
