const emptyProfile = {
  firstName: "",
  lastName: "",
  email: "",
  class: "",
  majorOne: "",
  majorTwo: "",
  majorThree: "",
  preferredPronouns: "",
  interestOne: "",
  interestTwo: "",
  interestThree: "",
  interestFour: "",
  interestFive: "",
  groupOne: "",
  groupTwo: "",
  groupThree: "",
  varsitySportOne: "",
  varsitySportTwo: "",
  affinitySportOne: "",
  affinitySportTwo: "",
  affinitySportThree: "",
  greekLife: "",
  favorites: {
    movie: "",
    book: "",
    tvShow: "",
    artist: "",
  },
  bio: "",
  courseOne: {},
  courseTwo: {},
  courseThree: {},
  courseFour: {},
  courseFive: {},
  loading: false,
  errors: {},
  validProfile: true,
};

export default emptyProfile;
