const CandAinterests = [
  "Academic and Scientific Research",
  "Architecture",
  "Art and Design",
  "Astronomy",
  "Finance and Economics",
  "Business and Marketing",
  "Computer Science and Web Design",
  "Cultural and Social Studies",
  "Data Science",
  "Education",
  "Engineering",
  "English",
  "Environment and Sustainability",
  "Entrepreneurship",
  "Health Care and Medicine",
  "History and Philosophy",
  "Innovation and Technology",
  "International Relations",
  "Journalism and Media",
  "Government, Law, and Public Policy",
  "Linguistics",
  "Math and Statistics",
  "Natural and Physical Sciences",
  "Performing Arts",
];

const GHinterests = [
  "Animals and Pets",
  "Artistic Creation",
  "Baking and Cooking",
  "Board and Card Games",
  "Concerts and Festivals",
  "Clubs and Nightlife",
  "Home and Garden",
  "Media and Podcasts",
  "Movies",
  "Music",
  "Photography",
  "Plane, Trains, and Automobiles",
  "Playing Music ",
  "Reading and Writing",
  "Shopping and Fashion",
  "Theatre and Performing Arts",
  "Traveling",
  "TV/Shows",
  "Video Games",
];

const PAandWinterests = [
  "Baseball",
  "Basketball",
  "Boxing, MMA, and Wrestling",
  "Cycling",
  "Football",
  "Golf",
  "Hiking, Backpacking, and Camping",
  "Hunting and Fishing",
  "Meditation and Yoga",
  "Motor Sports",
  "Food and Nutrition",
  "Physical Exercise and Working Out",
  "Sleep and Recovery",
  "Soccer",
  "Swimming and Diving",
  "Tennis",
  "Track and Field",
  "Water Sports",
  "Winter Sports",
];

export { CandAinterests, PAandWinterests, GHinterests };
