const majors = (
  <datalist id="majors">
    <option value="Africana Studies" />
    <option value="American Studies" />
    <option value="Anthropology" />
    <option value="Applied Mathematics" />
    <option value="Applied Mathematics-Biology" />
    <option value="Applied Mathematics-Computer Science" />
    <option value="Applied Mathematics-Economics" />
    <option value="Archaeology and the Ancient World" />
    <option value="Architecture" />
    <option value="Astronomy" />
    <option value="Behavioral Decision Sciences" />
    <option value="Biochemistry and Molecular Biology" />
    <option value="Biology" />
    <option value="Biomedical Engineering" />
    <option value="Biophysics" />
    <option value="Business, Entrepreneurship, and Organizations" />
    <option value="Chemical Physics" />
    <option value="Chemistry" />
    <option value="Classics" />
    <option value="Cognitive Neuroscience" />
    <option value="Cognitive Science" />
    <option value="Comparative Literature" />
    <option value="Computational Biology" />
    <option value="Computer Science" />
    <option value="Computer Science-Economics" />
    <option value="Contemplative Studies" />
    <option value="Development Studies" />
    <option value="Early Modern World" />
    <option value="East Asian Studies" />
    <option value="Economics" />
    <option value="Education Studies" />
    <option value="Egyptology and Assyriology" />
    <option value="Engineering" />
    <option value="Engineering and Physics" />
    <option value="English" />
    <option value="Environmental Studies" />
    <option value="Ethnic Studies" />
    <option value="French and Francophone Studies" />
    <option value="Gender and Sexuality Studies" />
    <option value="Geological Sciences" />
    <option value="Geology-Biology" />
    <option value="Geology-Chemistry" />
    <option value="Geology-Physics/Mathematics" />
    <option value="German Studies" />
    <option value="Health and Human Biology" />
    <option value="Hispanic Literatures and Cultures" />
    <option value="History" />
    <option value="History of Art and Architecture" />
    <option value="International and Public Affairs" />
    <option value="International Relations" />
    <option value="Italian Studies" />
    <option value="Judaic Studies" />
    <option value="Latin American and Caribbean Studies" />
    <option value="Linguistics" />
    <option value="Literary Arts" />
    <option value="Mathematics" />
    <option value="Mathematics-Computer Science" />
    <option value="Mathematics-Economics" />
    <option value="Medieval Cultures" />
    <option value="Middle East Studies" />
    <option value="Modern Culture and Media" />
    <option value="Music" />
    <option value="Neuroscience" />
    <option value="Philosophy" />
    <option value="Physics" />
    <option value="Physics and Philosophy" />
    <option value="Political Science" />
    <option value="Portuguese and Brazilian Studies" />
    <option value="Psychology" />
    <option value="Public Health" />
    <option value="Public Policy" />
    <option value="Religious Studies" />
    <option value="Science, Technology, and Society" />
    <option value="Slavic Studies" />
    <option value="Social Analysis and Research" />
    <option value="Sociology" />
    <option value="South Asian Studies" />
    <option value="Statistics" />
    <option value="Theatre Arts and Performance Studies" />
    <option value="Undecided" />
    <option value="Urban Studies" />
    <option value="Visual Art" />
  </datalist>
);

export default majors;
