const profileViewState = {
  // Required
  firstName: "",
  lastName: "",
  classYear: "",
  major1: "",
  major2: "",
  major3: "",
  preferredPronouns: "",
  interests1: [],
  interests2: [],
  interests3: [],
  courses: [{}, {}, {}, {}, {}],
  imageUrl: "",
  // Required Edits
  firstName_: "",
  lastName_: "",
  classYear_: "",
  major1_: "",
  major2_: "",
  major3_: "",
  preferredPronouns_: "",
  interests1_: [],
  interests2_: [],
  interests3_: [],
  courseColor: "",
  addCourseCode: "",
  addCourseName: "",
  addCourseColor: "",
  //Optional
  bio: "",
  varsitySport1: "",
  varsitySport2: "",
  group1: "",
  group2: "",
  group3: "",
  greekLife: "",
  instrument1: "",
  instrument2: "",
  instrument3: "",
  pickUpSport1: "",
  pickUpSport2: "",
  pickUpSport3: "",
  pet1: "",
  pet2: "",
  pet3: "",
  favoriteBook: "",
  favoriteMovie: "",
  favoriteShow: "",
  favoriteArtist: "",
  // Optional Edits
  bio_: "",
  varsitySport1_: "",
  varsitySport2_: "",
  group1_: "",
  group2_: "",
  group3_: "",
  greekLife_: "",
  instrument1_: "",
  instrument2_: "",
  instrument3_: "",
  pickUpSport1_: "",
  pickUpSport2_: "",
  pickUpSport3_: "",
  pet1_: "",
  pet2_: "",
  pet3_: "",
  favoriteBook_: "",
  favoriteMovie_: "",
  favoriteShow_: "",
  favoriteArtist_: "",
  // Dialog Controls
  imageOpen: false,
  basicOpen: false,
  bioOpen: false,
  groupsOpen: false,
  varsityOpen: false,
  greekOpen: false,
  interestsOpen: false,
  instrumentsOpen: false,
  pickUpSportsOpen: false,
  petsOpen: false,
  favoritesOpen: false,
  colorOpen: [false, false, false, false, false],
  addOpen: false,
  removeOpen: false,
  crop: false,
  // Miscellaneous
  firstTime: false,
  loading: true,
  tabIndex: 0,
};

export default profileViewState;
