const profileViewState = {
  // Required
  firstName: "",
  lastName: "",
  classYear: "",
  major1: "",
  major2: "",
  major3: "",
  preferredPronouns: "",
  interests1: [],
  interests2: [],
  interests3: [],
  course1: { code: "", name: "", color: "" },
  course2: { code: "", name: "", color: "" },
  course3: { code: "", name: "", color: "" },
  course4: { code: "", name: "", color: "" },
  course5: { code: "", name: "", color: "" },
  imageUrl: "",
  // Required Edits
  firstName_: "",
  lastName_: "",
  classYear_: "",
  major1_: "",
  major2_: "",
  major3_: "",
  preferredPronouns_: "",
  //Optional

  bio: "",
  addCourseCode: "",
  addCourseName: "",
  addCourseColor: "",
  affinitySports: [],
  affinitySportOne: "",
  affinitySportTwo: "",
  affinitySportThree: "",
  bio_: "",
  bioOpen: false,

  class_: "",

  createdAt: "",
  delete: false,
  email: "",
  favorites: {},
  favoriteBook: "",
  favoriteMovie: "",
  favoriteShow: "",
  favoriteArtist: "",

  firstTime: false,
  greekLife: "",
  greekOpen: false,
  greekLife_: "",
  groups: [],
  groupOne: "",
  groupTwo: "",
  groupThree: "",

  newInterestsOpen: false,
  interests1_: [],
  interests2_: [],
  interests3_: [],
  addOpen: false,
  removeOpen: false,
  deleteCourse: false,

  userId: "",
  varsityOpen: false,
  varsitySports: [],
  varsitySportOne: "",
  varsitySportTwo: "",
  varsitySport1: "",
  varsitySport2: "",
  groupOpen: false,
  basicOpen: false,
  interestsOpen: false,
  favoritesOpen: false,
  imageOpen: false,
  loading: true,
  colorOpen: [false, false, false, false, false],
  courseColor: "",
  courseColor0: "",
  courseColor1: "",
  courseColor2: "",
  courseColor3: "",
  courseColor4: "",
  tabIndex: 0,
};

export default profileViewState;
