const classYears = [
  {
    value: "2022",
    label: "2022",
  },
  {
    value: "2023",
    label: "2023",
  },
  {
    value: "2024",
    label: "2024",
  },
  {
    value: "2025",
    label: "2025",
  },
];

const interests = [
  { value: "Tennis", label: "Tennis" },
  { value: "Basketball", label: "Basketball" },
  { value: "Baseball", label: "Baseball" },
];

const majors = [
  { value: "Africana Studies", label: "Africana Studies" },
  { value: "American Studies", label: "American Studies" },
  { value: "Anthropology", label: "Anthropology" },
  { value: "Applied Mathematics", label: "Applied Mathematics" },
  {
    value: "Applied Mathematics-Biology",
    label: "Applied Mathematics-Biology",
  },
  { value: "Applied Mathematics-Computer Science", label: "" },
  { value: "Applied Mathematics-Economics", label: "" },
  { value: "Archaeology and the Ancient World", label: "" },
  { value: "Architecture", label: "" },
  { value: "Astronomy", label: "" },
  { value: "Behavioral Decision Sciences", label: "" },
  { value: "Biochemistry and Molecular Biology", label: "" },
  { value: "Biology", label: "" },
  { value: "Biomedical Engineering", label: "" },
  { value: "Biophysics", label: "" },
  { value: "Business, Entrepreneurship, and Organizations", label: "" },
  { value: "Chemical Physics", label: "" },
  { value: "Chemistry", label: "" },
  { value: "Classics", label: "" },
  { value: "Cognitive Neuroscience", label: "" },
  { value: "Cognitive Science", label: "" },
  { value: "Comparative Literature", label: "" },
  { value: "Computational Biology", label: "" },
  { value: "Computer Science", label: "" },
  { value: "Computer Science-Economics", label: "" },
  { value: "Contemplative Studies", label: "" },
  { value: "Development Studies", label: "" },
  { value: "Early Modern World", label: "" },
  { value: "East Asian Studies", label: "" },
  { value: "Economics", label: "" },
  { value: "Education Studies", label: "" },
  { value: "Egyptology and Assyriology", label: "" },
  { value: "Engineering", label: "" },
  { value: "Engineering and Physics", label: "" },
  { value: "English", label: "" },
  { value: "Environmental Studies", label: "" },
  { value: "Ethnic Studies", label: "" },
  { value: "French and Francophone Studies", label: "" },
  { value: "Gender and Sexuality Studies", label: "" },
  { value: "Geological Sciences", label: "" },
  { value: "Geology-Biology", label: "" },
  { value: "Geology-Chemistry", label: "" },
  { value: "Geology-Physics/Mathematics", label: "" },
  { value: "German Studies", label: "" },
  { value: "Health and Human Biology", label: "" },
  { value: "Hispanic Literatures and Cultures", label: "" },
  { value: "History", label: "" },
  { value: "History of Art and Architecture", label: "" },
  { value: "International and Public Affairs", label: "" },
  { value: "International Relations", label: "" },
  { value: "Italian Studies", label: "" },
  { value: "Judaic Studies", label: "" },
  { value: "Latin American and Caribbean Studies", label: "" },
  { value: "Linguistics", label: "" },
  { value: "Literary Arts", label: "" },
  { value: "Mathematics", label: "" },
  { value: "Mathematics-Computer Science", label: "" },
  { value: "Mathematics-Economics", label: "" },
  { value: "Medieval Cultures", label: "" },
  { value: "Middle East Studies", label: "" },
  { value: "Modern Culture and Media", label: "" },
  { value: "Music", label: "" },
  { value: "Neuroscience", label: "" },
  { value: "Philosophy", label: "" },
  { value: "Physics", label: "" },
  { value: "Physics and Philosophy", label: "" },
  { value: "Political Science", label: "" },
  { value: "Portuguese and Brazilian Studies", label: "" },
  { value: "Psychology", label: "" },
  { value: "Public Health", label: "" },
  { value: "Public Policy", label: "" },
  { value: "Religious Studies", label: "" },
  { value: "Science, Technology, and Society", label: "" },
  { value: "Slavic Studies", label: "" },
  { value: "Social Analysis and Research", label: "" },
  { value: "Sociology", label: "" },
  { value: "South Asian Studies", label: "" },
  { value: "Statistics", label: "" },
  { value: "Theatre Arts and Performance Studies", label: "" },
  { value: "Undecided", label: "" },
  { value: "Urban Studies", label: "" },
  { value: "Visual Art", label: "" },
];

export { classYears, interests, majors };
